### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Evolving666** [liangjingkanji/DrakeTyporaTheme#1]
大神，可否出个黑色主题的，晚上码代码用

**Comment by BarryAlanPan** [comment]
附议

**Comment by liangjingkanji** [comment]
好的，我最近研究下暗色模式用什么配色好

**Comment by OrdinaryYZH** [comment]
3个月过去了~

**Comment by liangjingkanji** [comment]
找了个新的坑爹工作累死了, 等我辞职换个公司

**Comment by OrdinaryYZH** [comment]
> 找了个新的坑爹工作累死了, 等我辞职换个公司

哈哈，好的

**Comment by hovenjay** [comment]
建议文字加粗的效果修改为正常的加粗效果，而不是加上黑色底色

**Comment by liangjingkanji** [comment]
> 建议文字加粗的效果修改为正常的加粗效果，而不是加上黑色底色

那会不会和标题冲突

**Comment by hovenjay** [comment]
> > 建议文字加粗的效果修改为正常的加粗效果，而不是加上黑色底色
> 
> 那会不会和标题冲突

这个不会的

**Comment by liangjingkanji** [comment]
> > > 建议文字加粗的效果修改为正常的加粗效果，而不是加上黑色底色
> > 
> > 
> > 那会不会和标题冲突
> 
> 这个不会的

现在的加粗效果觉得可以接收吗?

**Comment by hovenjay** [comment]
> > > > 建议文字加粗的效果修改为正常的加粗效果，而不是加上黑色底色
> > > 
> > > 
> > > 那会不会和标题冲突
> > 
> > 
> > 这个不会的
> 
> 现在的加粗效果觉得可以接收吗?

**加粗**，我个人觉得还是直接**加粗**字体就行，加底色的方式不叫**加粗**

**Comment by Newt0n** [comment]
> 大神，可否出个黑色主题的，晚上码代码用

非常期待 Dark Mode，大神加油

**Comment by uclort** [comment]
@liangjingkanji 大佬，21 年过了一半了，还能等到黑色主题么。🤣

**Comment by liangjingkanji** [comment]
> @liangjingkanji 大佬，21 年过了一半了，还能等到黑色主题么。🤣

生活艰辛, 世事难料.   未来可期, 会有的.  关于这个暗色模式我肯定会着重设计的

**Comment by imageslr** [comment]
大佬生活不易啊🤣

我这里有些暗色主题，大家可以先凑合用： https://github.com/imageslr/typora-theme-bear

**Comment by liangjingkanji** [comment]
@imageslr 失业挺久了:relaxed:

**Comment by liangjingkanji** [comment]
已更新暗色主题, 亮色主题也更加扁平化, 有提议或者问题可以反馈或者pr

![截图](https://raw.githubusercontent.com/liangjingkanji/DrakeTyporaTheme/master/thumbnail-dark.png)

**Comment by liangjingkanji** [comment]
新增 Purple 风格

![](https://raw.githubusercontent.com/liangjingkanji/DrakeTyporaTheme/master/img/thumbnail-purple.png)

**Comment by liangjingkanji** [comment]
新增 Ayu 风格

![](https://raw.githubusercontent.com/liangjingkanji/DrakeTyporaTheme/master/img/thumbnail-ayu.png)
