### ISSUE TITLE
导出html后，任务列表不显示图标

### ISSUE THREAD

**Issue by YoungYuan1971** [liangjingkanji/DrakeTyporaTheme#100]
### 描述问题
typora使用Drake Vue主题，导出html后，任务列表不显示图标。更换为github等内置主题可以在html中正常显示

### 期望结果
期望能得到帮助解决！

### 截图
<img width="430" alt="iShot_2022-08-12_12 36 58" src="https://user-images.githubusercontent.com/50771066/184285899-9cc6c39a-8e81-408e-a8fe-c1837abf150d.png">

### 系统 (建议使用最新Typora版本)
 - OS：MacOS12.5 Monterey
 - Theme：Drake Vue
 - Typora：Version 1.3.7

**Comment by liangjingkanji** [comment]
官方问题无法通过修复(除非我去除自定义任务列表样式效果), 请反馈给官方修复此问题

**Comment by YoungYuan1971** [comment]
3Q
