### ISSUE TITLE
classDiagram  mermaid 全黑的，看不清

### ISSUE THREAD

**Issue by aerfensi** [liangjingkanji/DrakeTyporaTheme#102]
### 描述问题

![image](https://user-images.githubusercontent.com/23309953/187398161-1bb2482e-e0f6-40a8-9440-09de0d794fb1.png)

### 系统 (建议使用最新Typora版本)
 - OS：win10
 - Theme ：所有暗色主题，以及部分亮色主题
 - Typora Version 1.3.8

**Comment by liangjingkanji** [comment]
请提供文本内容

**Comment by aerfensi** [comment]
比如这种

```mermaid
classDiagram
	Object <|-- A
	A : show()
	
	A <|-- B
	A <|-- C
	C : show()
	
	B <|-- D
	C <|-- D
```

主题选drakedark

**Comment by aerfensi** [comment]
不好意思，代码块有点难贴，就是类似下面这种
```

```mermaid
classDiagram
	Object <|-- A
	A : show()
	
	A <|-- B
	A <|-- C
	C : show()
	
	B <|-- D
	C <|-- D
```

```

**Comment by liangjingkanji** [comment]
看情况是没有兼容 `classDiagram` 样式, 之前仅对`sequenceDiagram`进行处理

**Comment by aerfensi** [comment]
还有flowchart、stateDiagram、journey、erDiagram这几种图也帮忙看下，在暗色主题下显示也不清晰。我直接在 https://mermaid-js.github.io/mermaid/#/flowchart 这里随便复制了些示例代码块试了下。

**Comment by liangjingkanji** [comment]
你能将不兼容的示例文本贴出来吗? 我对于流程图语法不熟

**Comment by aerfensi** [comment]
flowchart TD
    Start --> Stop

================================

stateDiagram
    [*] --> Still
    Still --> [*]

    Still --> Moving
    Moving --> Still
    Moving --> Crash
    Crash --> [*]

=================

journey
    title My working day
    section Go to work
      Make tea: 5: Me
      Go upstairs: 3: Me
      Do work: 1: Me, Cat
    section Go home
      Go downstairs: 5: Me
      Sit down: 5: Me

==========================

erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    CUSTOMER }|..|{ DELIVERY-ADDRESS : uses

**Comment by aerfensi** [comment]
```
flowchart TD
    Start --> Stop
```

```
stateDiagram
    [*] --> Still
    Still --> [*]

    Still --> Moving
    Moving --> Still
    Moving --> Crash
    Crash --> [*]
```

```
journey
    title My working day
    section Go to work
      Make tea: 5: Me
      Go upstairs: 3: Me
      Do work: 1: Me, Cat
    section Go home
      Go downstairs: 5: Me
      Sit down: 5: Me
```

```
erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    CUSTOMER }|..|{ DELIVERY-ADDRESS : uses
```

**Comment by liangjingkanji** [comment]
请注意markdown格式, 添加`mermaid`语法

**Comment by aerfensi** [comment]
是的，只要在上面的代码中加上mermaid就行了，我没办法在评论里加，加上后被GitHub解析了，变成图了，不是代码了

**Comment by liangjingkanji** [comment]
即使被github渲染, 我也可以读取到代码的

**Comment by liangjingkanji** [comment]
已修复请重新下载

**Comment by liangjingkanji** [comment]
关于`stateDiagram`的生成的图显示非常大是Typora官方问题, 请反馈给官方
