### ISSUE TITLE
导出 PDF 之后部分字体发虚

### ISSUE THREAD

**Issue by doufum** [liangjingkanji/DrakeTyporaTheme#104]
### 描述问题
用 DrakeJuejin 导出 pdf 之后，部分字体发虚
<img width="1266" alt="图片" src="https://user-images.githubusercontent.com/6191406/188124784-4e1690ef-940c-4491-a2c8-a6dd82b08f51.png">

### 期望结果
字体和 markdown 看到的一致

### 系统 (建议使用最新Typora版本)
 - OS：MacOS
 - Theme ：DrakeJuejin
 - Typora Version：1.4.2

**Comment by liangjingkanji** [comment]
导出PDF请让Typora官方修复, 我目前无能为力

**Comment by domeniczz** [comment]
这个应该是 Typora 的 bug，导出时候会出一些奇奇怪怪的问题

多导出几次就好了，总有一次是正常的

**Comment by liangjingkanji** [comment]
补充: PosggreSQL是错别字, 应当叫 `PostgreSQL`

**Comment by doufum** [comment]
> 补充: PosggreSQL是错别字, 应当叫 `PostgreSQL`

谢谢指正😄
