### ISSUE TITLE
代码滚动时和行号重叠

### ISSUE THREAD

**Issue by xtsang** [liangjingkanji/DrakeTyporaTheme#108]
### 描述问题
#39 按照此方法打开滚动条，代码滚动时会和行号重叠

### 截图
![uTools_1666776275241](https://user-images.githubusercontent.com/55629892/197991497-10178920-7cc6-4e1e-bf44-148dd522383a.png)

### 系统 (建议使用最新Typora版本)
 - OS: windows 22H2 build 22621.675
 - Theme: Drake
 - Typora Version: 1.4.8

**Comment by liangjingkanji** [comment]
可能是Windows版本特有的问题, 等我抽空用Windows复现下问题

**Comment by liangjingkanji** [comment]
已修复亮色主题存在的此问题
