### ISSUE TITLE
超喜欢这个主题,刘总啥时候整个obsidian的同款呗,含泪血书

### ISSUE THREAD

**Issue by jackey-jiang** [liangjingkanji/DrakeTyporaTheme#109]
### 描述问题
现在换到obsidian,但还是刘总的这个主题用的舒服,没办法,就是这么念旧 - -!

**Comment by liangjingkanji** [comment]
等我开始使用Obsidian时候吧, 目前我没有这个精力推出新的主题. 本主题遵守开源社区共同开发完善
