### ISSUE TITLE
简体字显示为繁体

### ISSUE THREAD

**Issue by suiahae** [liangjingkanji/DrakeTyporaTheme#111]
### 描述问题
Windows 11 22H2 下，选用 Drake 系列主题（默认，未修改），简体字显示为繁体。

### 如何复现问题
切换到任意 Drake 主题

### 期望结果
简体字显示为简体

### 截图
默认GitHub主题：
![图片](https://user-images.githubusercontent.com/45323123/200844645-f4198c5f-9c8f-4547-a48a-6e935eb3336a.png)
Drake Vue：
![图片](https://user-images.githubusercontent.com/45323123/200844751-cef03b37-4c6f-4954-8f48-a122156bc9aa.png)
Drake Ayu：
![图片](https://user-images.githubusercontent.com/45323123/200844976-e30a3f5b-9e78-4aed-a930-589a95d4842d.png)

### 系统 (建议使用最新Typora版本)
 - OS：Windows 11 22H2 
 - Theme：2.9.1 Drake 系列所有主题
 - Typora Version：1.4.8

**Comment by liangjingkanji** [comment]
这与你安装的字体有关, 你找到修改字体的位置查看当前顺序应用的是哪个字体

**Comment by suiahae** [comment]
font.css 默认没有更改
![图片](https://user-images.githubusercontent.com/45323123/201001876-3094512f-1e56-4286-8892-50edfa807287.png)

对比显示效果和 Windows 已安装字体，发现使用的应该是“方正细圆繁体”。

安装 README.md 推荐的 HYZhengYuan 后恢复正常👍。

**Comment by liangjingkanji** [comment]
换别的字体也行, 字体名称根据顺序填写
