### ISSUE TITLE
使用上下标时下划线异常

### ISSUE THREAD

**Issue by xtsang** [liangjingkanji/DrakeTyporaTheme#113]
### 描述问题
使用上下标时下划线位置异常，如 Drake 主题中的 h2 标题和链接

### 截图
![uTools_1668399674252](https://user-images.githubusercontent.com/55629892/201574859-02f64d8c-3b73-443c-845e-8f155d9dacfb.png)
![uTools_1668399683677](https://user-images.githubusercontent.com/55629892/201574870-e26da1bb-50a0-4aa1-a53e-5cba5236b681.png)

### 系统 (建议使用最新Typora版本)
 - OS: windows 22H2 build 22621.675
 - Theme: Drake
 - Typora Version: 1.4.8

**Comment by liangjingkanji** [comment]
请贴上MD文件

**Comment by xtsang** [comment]
> 请贴上MD文件

## B^+^-Tree 索引与数据量

**Comment by liangjingkanji** [comment]
我无法修复此问题, 我可能得选择删除`适应标题宽度分割线`改为全屏宽度分割线了

**Comment by liangjingkanji** [comment]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/21078112/201839162-b2061d8d-3468-460a-96ea-b692fb4ee3a2.png">
