### ISSUE TITLE
希望作者能出一个Obsidian的Drake主题

### ISSUE THREAD

**Issue by Kohirus** [liangjingkanji/DrakeTyporaTheme#114]
### 描述问题

最近在使用 Obsidian，奈何发现没有一个主题能与 Drake 相媲美。喜欢 Typora 的这款 Drake 主题，但是 Typora 没有 Obsidian 组织文件的功能，想用 Obsidian，但是没有 Drake 这么钟意的主题。非常希望作者做一款 Obsidian 的 Drake 主题。

**Comment by callmedd** [comment]
同希望能有个obsidian的drake，最近才入手的obsidian，但是里面的主题跟drake比起来太菜了

**Comment by ZekunC** [comment]
不知道你想要的是哪种类型，是Drake的颜色？或是其他样式？我参考Typora的Vue主题做了一个Obsidian的主题 ，现已上架官方商店 [Obsidian-Typora-Vue-Theme](https://github.com/ZekunC/Obsidian-Typora-Vue-Theme) ，可以通过`Obsidian设置 -> 外观 -> Accent Color`修改为Drake的主题颜色 `#e95f59` 或你想要的其他任意颜色。（默认是Vue的绿色）

以下是其默认颜色
![image](https://raw.githubusercontent.com/ZekunC/Obsidian-Typora-Vue-Theme/master/high-res.png)

以下是我修改Accent Color得到的类似Drake-light的颜色 `#e95f59` ：

![](https://raw.githubusercontent.com/ZekunC/Obsidian-Typora-Vue-Theme/master/drake-light.png)

**Comment by callmedd** [comment]
> 不知道你想要的是哪种类型，是Drake的颜色？或是其他样式？我参考Typora的Vue主题做了一个Obsidian的主题 ，现已上架官方商店 [Obsidian-Typora-Vue-Theme](https://github.com/ZekunC/Obsidian-Typora-Vue-Theme) ，可以通过`Obsidian设置 -> 外观 -> Accent Color`修改为Drake的主题颜色 `#e95f59` 或你想要的其他任意颜色。（默认是Vue的绿色）
> 
> 以下是其默认颜色 ![image](https://raw.githubusercontent.com/ZekunC/Obsidian-Typora-Vue-Theme/master/high-res.png)
> 
> 以下是我修改Accent Color得到的类似Drake-light的颜色 `#e95f59` ：
> 
> ![](https://raw.githubusercontent.com/ZekunC/Obsidian-Typora-Vue-Theme/master/drake-light.png)

简单的说就是想让一个md文件在typora中和在obsidian中看起来一模一样

**Comment by Kohirus** [comment]
![image](https://raw.githubusercontent.com/ZekunC/Obsidian-Typora-Vue-Theme/master/high-res.png)

这个看起来也很棒！希望图片可以默认居中显示。

**Comment by liangjingkanji** [comment]
早期我就有使用Obsidian但是我没有选中他, 就在刚刚为了确保我又使用了下

我依旧认为不符合我追求的优雅排版, 即使Ob功能更多且有更完善的文档管理但是我认为取舍之下我依然选择Typora(成为高贵付费用户)

由于主题制作对于我来说并不轻松, 而且我有很多开源项目需要持续维护(包括现在这个主题), 所以我没有精力去制作Obsidian主题, 我只是低端人口我绝大部分精力需要为了生活而奔波

**Comment by Kohirus** [comment]
好的，但还是很谢谢作者能提供如此精美的Typora主题。
