### ISSUE TITLE
为什么我用了主题之后，字体还是黑色的，我记得之前还没有问题

### ISSUE THREAD

**Issue by a1029602653** [liangjingkanji/DrakeTyporaTheme#115]
### 描述问题
用的是Drake-google主题，然后整个界面的字体仍然是黑色的，我记得之前是蓝色的来着？

### 截图
![image](https://user-images.githubusercontent.com/39894592/206892722-aef79eb9-de34-4c76-837e-f484f880de40.png)

### 系统 (建议使用最新Typora版本)
 无论是Ubuntu还是Windows11都是这样的。请求大佬支援！！！

**Comment by liangjingkanji** [comment]
`drake-google`文字颜色一直是 `#202124`, 偏黑色
