### ISSUE TITLE
請教一下，為何使用『Drake Juejin』佈景時，編輯器顯示都正常，但輸出到PDF則標ˇ題會不對齊!

### ISSUE THREAD

**Issue by afgnsu** [liangjingkanji/DrakeTyporaTheme#116]
### 如何复现问题
輸出到PDF時發現

### 期望结果
希望能改善，謝謝您 ^_^

### 截图
![2022-12-23_163439](https://user-images.githubusercontent.com/7204469/209303212-c1f70bbb-585c-4f81-851c-fdff447745dc.png)

![2022-12-23_163704](https://user-images.githubusercontent.com/7204469/209303237-dbc531ad-cd9a-46cd-9ed0-5ebc613412ab.png)

![2022-12-23_164142](https://user-images.githubusercontent.com/7204469/209303256-988193b7-b5f9-4f99-9122-6ef3683d5552.png)

![2022-12-23_164207](https://user-images.githubusercontent.com/7204469/209303264-5ddbcc2c-5e6a-47a8-8257-2fb43903ab94.png)

![2022-12-23_164447](https://user-images.githubusercontent.com/7204469/209303546-ae3d5cad-ae60-4dbc-a750-1322143ffc33.png)

![2022-12-23_164633](https://user-images.githubusercontent.com/7204469/209304130-bdd13737-ba23-462f-a12f-a5360fde33fa.png)

### 系统 (建议使用最新Typora版本)
 - OS：Windows 10 Professional 繁體中文版
 - Theme：Drake Juejin
 - Typora Version：1.3.6

**Comment by liangjingkanji** [comment]
很遗憾的是Typora的PDF导出总是会缺失某些css样式, 我目前能做到的最佳办法是删除`[]`二级标题的修饰

**Comment by afgnsu** [comment]
收到，謝謝。
