### ISSUE TITLE
安装方法有点容易误解

### ISSUE THREAD

**Issue by domg007** [liangjingkanji/DrakeTyporaTheme#118]
#### 示意的安装步骤：

> 1. 首先确定已安装Typora
> 2. 通过设置 -> 外观 -> 打开主题文件夹打开theme目录
> 3. 复制所有文件到theme目录下然后重启, 选择菜单栏 -> 主题即可

我是第一次安装Typora主题，根据安装步骤，把下载的主题直接解压到theme目录。

再根据步骤重启，却怎么也没找到新主题。

尝试几次无果后，去下载了其他的主题，才发现问题所在。

> Typora是以css文件来发现主题的，而下载的压缩包内是一个`DrakeTyporaTheme-master`的文件夹。
>
> 所以我解压后，最终的目录结构是
>
> `...\Typora\themes\DrakeTyporaTheme-master`

### 期望结果

或许可以去掉压缩包内的根目录，或者优化下安装步骤

### 系统 (建议使用最新Typora版本)

 - OS
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
已修复README的描述
