### ISSUE TITLE
代码区 != 会自动转成 ≠ ，希望把这个功能关闭

### ISSUE THREAD

**Issue by leongongye** [liangjingkanji/DrakeTyporaTheme#119]
如下代码：
```
public class CarController() {
    public RestfulResult makeCarDrive(Integer carId) {
        Car car = carManager.getCarById(carId);
        assert car != null;
        carManager.makeCarDrive(car);
        //...略
    }
}
```

渲染出来：

<img width="612" alt="图片" src="https://user-images.githubusercontent.com/15917687/210514515-7de20de7-c2ba-4578-8469-633acf9b4b38.png">

**Comment by leongongye** [comment]
自己改字体了。
建议是：code block 最好【保持原样】

**Comment by liangjingkanji** [comment]
抱歉无法采纳建议, 理由:

1. 这是目前最流行的编码字体, 且其是主流IDE的默认字体, 无法满足所有只能满足大部分用户
2. 本主题非常推荐使用连字特性(ligatures)
3. 本主题已经在README中有提示该问题

<br>

> 如果发生符号粘连, 那是主题内置字体JetBrainsMono的特性`ligatures`, 如不喜欢可自行删除: [#75](https://github.com/liangjingkanji/DrakeTyporaTheme/issues/75)

<br>
本问题将会置顶 🔝
