### ISSUE TITLE
代码格式错乱，粘贴进去好好的，已重新打开typora就错乱了

### ISSUE THREAD

**Issue by iwanghaifeng** [liangjingkanji/DrakeTyporaTheme#120]
### 描述问题
使用typora1.4.8
主题下载2.9.2
代码格式错乱，粘贴进去好好的，已重新打开typora就错乱了

### 如何复现问题
1、选择typora自带主题，新建一个文档，输入一个yaml或者xml等等格式的代码。关闭软件重新打开，格式显示正常
2、选择Drake任一主题，打开上面文档，或者重新新建一个文档，重复上面操作，重新打开typora后格式错乱，空格有的变成一个，有的变成3个，还有的直接没有缩进了

### 期望结果
正常显示

### 截图
默认使用typora自带主题例如Github正常显示的截图：
![image](https://user-images.githubusercontent.com/122277933/211308058-df1c036b-274f-4f04-84a8-a40e9882b30e.png)

选择任一Drake主题后，重新打开typora，格式就变成这样了，非常影响使用：
![image](https://user-images.githubusercontent.com/122277933/211307747-f275ba54-4a22-40b7-8301-9b3bd4446743.png)

### 系统 (建议使用最新Typora版本)
 - OS：Windows 11 专业工作站版
 - Theme ：任一Drake主题
 - Typora Version：1.4.8

**Comment by iwanghaifeng** [comment]
如何不格式化代码，粘进去什么样就显示什么样。只渲染下代码颜色就行

**Comment by liangjingkanji** [comment]
什么问题, 建议去设置里面看下缩进或者可能是语言本身不支持缩进
