### ISSUE TITLE
字体看起来很细

### ISSUE THREAD

**Issue by Zps977** [liangjingkanji/DrakeTyporaTheme#122]
### 描述问题
没修改字体，都是默认，汉仪正圆字体也安装了，但是中文字体感觉很细，没有图片看起来饱满

### 截图
图片左边是主题效果图，右边是在我电脑显示的样式
![image](https://user-images.githubusercontent.com/59304920/219843976-085db7ac-e949-42a8-b679-a42d63a47420.png)

### 系统 (建议使用最新Typora版本)
 - OS win11
 - Theme Drake Light
 - Typora Version 1.4.8

**Comment by liangjingkanji** [comment]
中文字体有粗细多个版本, 你可以选择不安装细的版本他就只能使用更粗的版本了1

**Comment by liangjingkanji** [comment]
突然发现你是windows? windows字体显示效果很差, 建议你直接换mac吧
