### ISSUE TITLE
希望排除一些文件再发 release

### ISSUE THREAD

**Issue by ShiinaKaze** [liangjingkanji/DrakeTyporaTheme#124]
### 描述问题
希望作者在 release 中把 `.github`,`.gitignore` 文件排除掉

### 期望结果
![image](https://user-images.githubusercontent.com/89641145/220913882-f3fc7d92-3fd4-4917-ba6d-d47bc077d01b.png)

### 截图
![image](https://user-images.githubusercontent.com/89641145/220913593-5c4d443d-093d-48db-bc1f-2fadb63a7098.png)

### 系统 (建议使用最新Typora版本)
 - OS Windows
 - Theme DrakeTyporaTheme
 - Typora Version 1.5.8

**Comment by liangjingkanji** [comment]
因为我是996人种，我没时间去做排除文件这些活

**Comment by ShiinaKaze** [comment]
好吧，谢谢。
