### ISSUE TITLE
关于一个边框的实现

### ISSUE THREAD

**Issue by wenjiazhengyyds** [liangjingkanji/DrakeTyporaTheme#125]
### 描述问题

想请教您一下，您这个红色的圆边框是怎么实现的呀

### 截图
![image](https://user-images.githubusercontent.com/124243252/222329365-78f5c7ae-3088-4199-b7ae-53d7516e8f74.png)

**Comment by liangjingkanji** [comment]
打开本项目的`README.md`就可以看到Markdown源码
