### ISSUE TITLE
请问Drake-juejin这个怎么取消背景的方格呀？

### ISSUE THREAD

**Issue by Ranpeki** [liangjingkanji/DrakeTyporaTheme#126]
### 描述问题
谢谢作者，很喜欢这系列的主题！
只有Drake-juejin这一个主题是方格背景，看习惯白底了，想问一下怎么处理呢~

**Comment by liangjingkanji** [comment]
[删除这一行](https://github.com/liangjingkanji/DrakeTyporaTheme/blob/da04902d85fe579f6d94a5c54812fc34632015c9/drake-juejin.css#L82)
