### ISSUE TITLE
新增样式建议

### ISSUE THREAD

**Issue by zl02655931** [liangjingkanji/DrakeTyporaTheme#127]
### 描述问题
东哥，感谢您提供的样式，可以说是typora中最强的主题，最近在翻typora其他主题时发现了这款觉得很有意思，https://theme.typora.io/theme/dyzj/，
希望能内置到您的主题中

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
颜色太花里胡哨不符合本主题设计规范
