### ISSUE TITLE
行间距问题

### ISSUE THREAD

**Issue by Traserve** [liangjingkanji/DrakeTyporaTheme#128]
链接间距有点挤，而且这个二级标题占得位置上下有点太宽了（个人感觉）
![image](https://user-images.githubusercontent.com/17785306/226095891-51d6365d-d1da-4e5c-a9b9-e1ebbe50a891.png)
![image](https://user-images.githubusercontent.com/17785306/226095902-1b22c1f2-971a-429d-b339-b311253fffe6.png)

**Comment by liangjingkanji** [comment]
请同时提供markdown源码

**Comment by liangjingkanji** [comment]
<img width="219" alt="image" src="https://user-images.githubusercontent.com/21078112/227103737-06deda8f-daa1-4ee3-a6ec-8b92415c3f5d.png">

无法复现你的问题, 请下次提供准确的版本号以及主题名称, 不要删除问题描述信息
