### ISSUE TITLE
引用块问题

### ISSUE THREAD

**Issue by ninglilili** [liangjingkanji/DrakeTyporaTheme#129]
### 描述问题
我想使得Drake主题中引用块的格式(p1)像Github格式那样(p2)，请问应该如何修改。

### 截图
![屏幕截图 2023-03-21 205541](https://user-images.githubusercontent.com/108405955/226613120-0fb56ec0-c74d-4ed4-882c-01694c07ae98.png)

![image](https://user-images.githubusercontent.com/108405955/226613036-1df1bcc7-f512-4ef7-a5f9-8389583e8e22.png)

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
在主题文件搜素`/*code block*/`按照其他主题修改

如果不知道如何修改代码请参考Typora官方网站
