### ISSUE TITLE
Drake Black主题如何调整引用块标识的颜色?

### ISSUE THREAD

**Issue by CCCarrot** [liangjingkanji/DrakeTyporaTheme#130]
### 描述问题
引用块标识的颜色和代码相同,背景也是同一色调,这样的话在引用里穿插代码会使得辨识度下降.

### 期望结果
比如标识引用块的竖线我想把改成蓝色或绿色.

### 截图
![QQ截图20230322200356](https://user-images.githubusercontent.com/38489942/226899723-c653b794-dd11-4df8-bbbc-969f33b353d1.png)

### 系统 (建议使用最新Typora版本)
 - OS win10
 - Theme Drake black
 - Typora Version

**Comment by liangjingkanji** [comment]
修为左侧竖线颜色: [位置](https://github.com/liangjingkanji/DrakeTyporaTheme/blob/da04902d85fe579f6d94a5c54812fc34632015c9/drake.css#L40)

**Comment by CCCarrot** [comment]
> 修为左侧竖线颜色: [位置](https://github.com/liangjingkanji/DrakeTyporaTheme/blob/da04902d85fe579f6d94a5c54812fc34632015c9/drake.css#L40)

感谢
