### ISSUE TITLE
Use the Drake theme markdown code block #How to adjust the comment color

### ISSUE THREAD

**Issue by Dog-Elder** [liangjingkanji/DrakeTyporaTheme#131]
### 描述问题
Use the Drake theme markdown code block #How to adjust the comment color

### 截图
![image](https://user-images.githubusercontent.com/56543937/227154171-d99aeb12-92a8-40e2-a488-1219bc6f1f6a.png)

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
什么主题?

**Comment by Dog-Elder** [comment]
就是默认的
![image](https://user-images.githubusercontent.com/56543937/227164514-ed01e662-be6f-493d-8117-0f31909f8afa.png)

**Comment by liangjingkanji** [comment]
修改为颜色`#FFD760`如何

**Comment by Dog-Elder** [comment]
> 修改为颜色`#FFD760`如何

好的,前端不太懂,主要是不知道在那个地方修改

**Comment by liangjingkanji** [comment]
这是标题我颜色调整为普通就好了
