### ISSUE TITLE
mermaid 渲染出现显示不全

### ISSUE THREAD

**Issue by wayne-ziqi** [liangjingkanji/DrakeTyporaTheme#132]
```mermaid
sequenceDiagram
    Client ->> + Server : Log in request
    Server ->> Server : check user name existence
```
上述mermaid在drake-google，drake，出现'existence'被截断错误
<img width="520" alt="image" src="https://user-images.githubusercontent.com/74848202/229811335-0ac8f148-8976-4d10-ba7f-81295d690ba3.png">

**Comment by liangjingkanji** [comment]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/21078112/231421652-00ef67f8-c25f-4dd8-a567-2778c7d2cfe2.png">

无论调整字体大小或者增加字符都无法复现你的问题

请尝试自行修复或者排查问题存在

**Comment by wayne-ziqi** [comment]
补充：Typora版本1.5.12 (6759)，macos 13.3，左右两端只要文字过长可能都会被遮挡，导出pdf图片正常
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/74848202/232402450-0e9b4948-e88b-4321-ad76-153cc3e14f97.png">

**Comment by liangjingkanji** [comment]
> 补充：Typora版本1.5.12 (6759)，macos 13.3，左右两端只要文字过长可能都会被遮挡，导出pdf图片正常 <img alt="image" width="1154" src="https://user-images.githubusercontent.com/74848202/232402450-0e9b4948-e88b-4321-ad76-153cc3e14f97.png">

你的流程图内容复制给我复现下, 在我无法复现的情况下是无法修复的

**Comment by wayne-ziqi** [comment]
好的，这是流程图源码
```
sequenceDiagram
    Client-->Client: Offline1111111111111
    Server --> Server: aaaaaaaaaaaaaaaaaaututfsa
    Client ->> + Server : Log-in request
    Client-->Client : Waiting
```
渲染结果：
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/74848202/232683879-83b25e43-0e0e-42d8-ac4d-a993df715956.png">
这是我使用的主题样式，[drake-google-old.zip](https://github.com/liangjingkanji/DrakeTyporaTheme/files/11258386/drake-google-old.zip)，仅调小代码块，latex的字体。但使用最新commit版本的.css问题仍然存在，所以可能不是字体问题？

**Comment by liangjingkanji** [comment]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/21078112/232772867-24913ef8-260b-47b1-b599-d59874d95d21.png">

我复现不出来这个问题, 或者你可以别用Windows了

**Comment by wayne-ziqi** [comment]
mba m1...，算了玄学问题不管了，不过导出pdf是正常的就可以了，感谢作者
