### ISSUE TITLE
暗色主题下mermaid子流程图（subgraph）渲染不正常

### ISSUE THREAD

**Issue by WinterG26** [liangjingkanji/DrakeTyporaTheme#133]
### 描述问题
使用暗色主题下，渲染mermaid的子流程时子流程框是白色的，很亮很突兀

### 如何复现问题
在暗色主题下使用mermaid子流程，例如：
``` mermaid
flowchart TB
	subgraph A [发标]
	direction TB
	A0("业务人员上传采购文件、邀请供应商并选择投标开始、结束时间(0)")-->A1
	A1("部门领导审核 (0 -> 100)")-->A2
	A2("综合部核稿分发 (100)")-->A3
	A3("综合部负责人审核 (100)")-->A4 & A5
	A4("风控部 (100)")-->A6
	A5("财务部 (100)")-->A6
	A6("公司领导会签 (100)")-->A7
	A7("总经理同意 (100)")-->A8
	A8("业务人员上传盖章版招标文件 (100 -> 200)")
	end
```

### 期望结果
子流程的框应该是较暗的颜色适配主题，例如深蓝、深紫。

### 截图
![image](https://user-images.githubusercontent.com/19148211/230533000-5ea293b9-be6e-477b-9a43-756a178b835a.png)

### 系统 (建议使用最新Typora版本)
 - OS Win11
 - Theme 所有暗色主题都有此问题
 - Typora Version 1.5.10

**Comment by WinterG26** [comment]
而且子流程框的说明文字颜色很虚，例如截图中的“发标“二字

**Comment by liangjingkanji** [comment]
已经修复
