### ISSUE TITLE
暗色主题下mermaid流程图中带文字的箭头渲染不正常

### ISSUE THREAD

**Issue by WinterG26** [liangjingkanji/DrakeTyporaTheme#135]
### 描述问题
暗色主题下mermaid流程图中带文字的箭头渲染不正常

### 如何复现问题
暗色主题下使用带文字的箭头
```
graph TB
B0("业务员申请更改投标结束时间")-->|测试|B1
B1("部门领导")-->B2
B2("分管领导")-->B3
B3("总经理")-->B4
B4>"改变投标结束时间"]
```
### 期望结果
箭头文字没有白色的底色

### 截图
![image](https://user-images.githubusercontent.com/19148211/231926691-616965c9-47e6-4584-8903-5b3a9dcf7594.png)

### 系统 (建议使用最新Typora版本)
 - OS Win11
 - Theme DrakeVue3
 - Typora Version 1.5.10

**Comment by liangjingkanji** [comment]
最新版本已修复此问题

顺便问下你 #132 问题你有出现吗? 我无法复现
