### ISSUE TITLE
建议增加版本信息

### ISSUE THREAD

**Issue by ryanxingql** [liangjingkanji/DrakeTyporaTheme#136]
东哥好，这个主题很赞！谢谢啦

有个小建议；能否在例如 [drake.css](https://github.com/liangjingkanji/DrakeTyporaTheme/blob/master/drake.css) 中加入版本信息，和 Releases 的 tag 一致。

因为大家需要在 Releases 中下载最新版本覆盖原有的主题文件；如果没有版本信息，我很难判断当前版本是否为最新。

只是一个小建议～

**Comment by liangjingkanji** [comment]
建议很好, 但是每次修改这类信息会浪费我时间和增加变动内容

并且大部分修改的都是一些用户反馈的小问题(绝大数人可能都不会遇到), 我一般不会频繁发布版本号, 所以release可能也不会发布新的版本号而是直接修改tag位置

我建议直接`watching`本仓库, 可以根据需要收到通知, 例如`release`每次发布都可以实现直接邮件通知更新(甚至可以任何提交内容)

**Comment by ryanxingql** [comment]
谢谢东哥回复，您的建议更好～

**Comment by liangjingkanji** [comment]
并且我自己使用的Git直接更新主题，我直接clone到theme目录
