### ISSUE TITLE
代码块不显示滚动条

### ISSUE THREAD

**Issue by DuanGeGit** [liangjingkanji/DrakeTyporaTheme#137]
### 描述问题
当代码块中一行代码太长超过显示宽度时，正常情况下typora默认是会出现横向滚动条的，但使用了Drake主题后，不会出现滚动条，使得代码显示不全，希望做一些优化，加上一个美观实用的横向滚动条，感谢作者，你做的主题很棒，本人很喜欢。
PS：代码块自动换行没有开
![2023-04-26_20-19-21](https://user-images.githubusercontent.com/127708956/234573686-22a85019-bd3e-43f0-8e0b-2557eb6757ee.png)

### 如何复现问题
代码如下，若是长度不够，请自行添加
```
class test{
    public static String getUserNameString(int id) throws CloneNotSupportedException, ArithmeticException,FileNotFoundException{
		  
    }
}
```

### 期望结果
希望做一些优化，当横向代码超出显示宽度，加上一个美观实用的横向滚动条。

### 截图
![2023-04-26_20-24-07](https://user-images.githubusercontent.com/127708956/234573748-dc8e48c8-de21-4390-90de-31df183be6b9.png)

### 系统 (建议使用最新Typora版本)
 - OS：Windows11
 - Theme：Drake
 - Typora Version：1.5.12

**Comment by DuanGeGit** [comment]
解决方案参考：https://github.com/liangjingkanji/DrakeTyporaTheme/issues/39#ref-issue-1423727057

**Comment by liangjingkanji** [comment]
滚动条太丑影响排版，所以隐藏了

也许我应该加入当常见问题中
