### ISSUE TITLE
Win下二级标题的下划线不显示

### ISSUE THREAD

**Issue by hwqchi** [liangjingkanji/DrakeTyporaTheme#138]
### 描述问题
安装完主题和字体后，预览几乎正常，但是二级标题的下划线没有显示

### 截图
![win二级标题的下划线不显示](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/6689097/87067f74-fa64-4326-9563-591fe3a2dd45)

### 系统 (建议使用最新Typora版本)
 - OS: Win11
 - Theme: 所有(v2.9.4)
 - Typora Version: v1.6.6

**Comment by liangjingkanji** [comment]
由于 #38 原因我无法修复此问题, 导致只能二级标题下划线

**Comment by liangjingkanji** [comment]
长时间无回复问题关闭
