### ISSUE TITLE
请问有办法整体放大字体大小吗？

### ISSUE THREAD

**Issue by devindang** [liangjingkanji/DrakeTyporaTheme#140]
### 描述问题
1080P的屏幕上，这个主题的字体太小了，很难看清楚

### 如何复现问题
切换到该主题

### 期望结果
期望字体大一点，像默认的那样大

### 截图
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/39517801/fb8b6056-f739-49e5-ba35-6124c9421f3a)
这是同样比例下的，和Github主题对比的截图

### 系统 (建议使用最新Typora版本)
 - OS:  Windows11
 - Theme:  Drake Dark
 - Typora Version:  1.6.7

**Comment by liangjingkanji** [comment]
主页和常见问题都写了如何调整字体大小，你还看不到吗？

什么都不看打开软件设置界面也知道调整字体大小

**Comment by liangjingkanji** [comment]
最好的办法换个Mac

**Comment by devindang** [comment]
> 主页和常见问题都写了如何调整字体大小，你还看不到吗？
> 
> 什么都不看打开软件设置界面也知道调整字体大小

不好意思，谢谢~
