### ISSUE TITLE
关于深色主题Darke Dark 代码行号显示问的反馈(主题做的很好 start一下哈哈)

### ISSUE THREAD

**Issue by Hshilong** [liangjingkanji/DrakeTyporaTheme#141]
### 描述问题
该系列主题下的行号显示会影响后面的内容的显示

### 如何复现问题
None

### 期望结果
更改完毕

### 截图
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/127855702/2ed9df0d-f4dd-4a8d-8445-c7d0c1a52b05)

### 系统 (建议使用最新Typora版本)
 - OS Windows
 - Theme  Darke Dark
 - Typora Version 0.9.65(beta)

**Comment by liangjingkanji** [comment]
你这是自己向右移动还是打开文件默认就被行号遮挡?

**Comment by Hshilong** [comment]
在初次使用的时候会默认被行号挡住一部分,且行号的显示与正常的情况不一样,然后当我点击某行的代码的时候,字体就变成了右对齐,其他正常情况的文字也是右对齐的,但是当我重新启动的时候,这部分问题就消失了,经过我的测试,这个问题出现在主题切换的时候偶有发生
正常情况如下:
![new](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/127855702/a3a02d07-d731-441e-a16a-c8fc1cfed73e)
异常情况如下:
![question](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/127855702/45455020-91dd-4604-9c49-20061d262e0b)
小问题而已,只是发生在主题切换时,不影响使用!

**Comment by liangjingkanji** [comment]
那这个问题我认为是Typora引起的, 另外我切换主题还是无法复现你这个问题

**Comment by liangjingkanji** [comment]
你不打算反馈给官方的话我将关闭此问题
