### ISSUE TITLE
修改任务列表颜色

### ISSUE THREAD

**Issue by OTzzz23** [liangjingkanji/DrakeTyporaTheme#142]
### 描述问题
请问怎么修改任务列表的颜色？
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/132056100/d8d1a8b5-91cf-49a0-806c-0322008e1543)
图中部分字体是红色的，我想可以用颜色来区分优先级。

### 系统 (建议使用最新Typora版本)
 - OS: Win 11
 - Theme : Drake-juejin
 - Typora Version: 1.0.3

**Comment by liangjingkanji** [comment]
你这个需求我也不知道怎么实现，你去Typora官网看下文档或者问下作者怎么实现吧

**Comment by liangjingkanji** [comment]
截图部分字体颜色那是代码片段颜色，和任务列表没有关系
