### ISSUE TITLE
修改字体失败

### ISSUE THREAD

**Issue by Lay-Etamsylate** [liangjingkanji/DrakeTyporaTheme#145]
### 描述问题
已按照ReadMe中教程修改黄色部分，但不起作用
系统也已安装字体

### 截图
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/71595854/e89aedaf-059a-47e0-924b-08b19428c0e5)
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/71595854/364e1013-c638-4682-a1b8-75ff10b092e3)

### 系统 (建议使用最新Typora版本)
 - Windows 10
 - Typora Version 1.6.7

**Comment by Lay-Etamsylate** [comment]
> Windows安装字体以后需要重启软件生效, 有重启Typora吗?

重启过了 系统和软件都重启过，还是没用

**Comment by liangjingkanji** [comment]
那我也不知道原因了, 没遇到过, 你可以问下Typora作者或者打开调试工具看下加载到什么字体了
