### ISSUE TITLE
如何自定义Mermaid中甘特图(gantt)的大小

### ISSUE THREAD

**Issue by WinterG26** [liangjingkanji/DrakeTyporaTheme#146]
### 描述问题
甘特图的大小非常小，包括文字及图案，难以看清，不过对比发现Typora的默认主题也是如此

### 如何复现问题
使用Vue3主题并且修改到16号字体，甘特图中的文字和图案的大小都非常小难以看清。

### 期望结果
在配置文件中能配置图案及文字的大小。

### 截图
<img width="1175" alt="image" src="https://github.com/liangjingkanji/DrakeTyporaTheme/assets/19148211/c6d6d8af-dfba-486c-949a-970bf39b76a5">

### 系统 (建议使用最新Typora版本)
 - OS macOS ventura 13.5
 - Theme vue3
 - Typora Version 1.6.7

**Comment by liangjingkanji** [comment]
请提供甘特图的内容，因为作者并不使用甘特图

**Comment by WinterG26** [comment]
举例一个简单的甘特图
```mermaid
gantt
dateFormat yyyy-MM-dd
title 管理系统优化排期
section 系统优化
同步流程类功能与账号体系:	2023-08-28,20d
页面展示优化:						2023-08-28,60d
```

**Comment by liangjingkanji** [comment]
因为比较忙, 发布比较晚, 你现在再试下效果吧

<img width="1133" alt="image" src="https://github.com/liangjingkanji/DrakeTyporaTheme/assets/21078112/fc757945-8bc3-44b1-8098-d73c0522d0b2">

小文字这是Typora默认效果, 我修改文字大小会和图对不上, 所以我只修改文字颜色
