### ISSUE TITLE
怎么只修改大纲（目录）字体的大小和行距

### ISSUE THREAD

**Issue by helloo-word** [liangjingkanji/DrakeTyporaTheme#151]
大纲字体大小和正文内容同步了，怎么只修改大纲的字体大小，修改的小一点，还有行距

**Comment by liangjingkanji** [comment]
下载最新主题, [修改大纲字体大小位置](https://github.com/liangjingkanji/DrakeTyporaTheme/blob/9e258b7c98cacc2783b27b2b5c14db2ac4007332/drake/font.css#L44)

行距自己修改吧, 我也不会, 更多自定义请参考Typora官网文档说明
