### ISSUE TITLE
更换主题后html代码（部分？）无效

### ISSUE THREAD

**Issue by Milktea77** [liangjingkanji/DrakeTyporaTheme#152]
### 描述问题
原主题下 <font color="red">xxxxxxxxxxxxxxx</font> 正常显示红色
更换任意drake主题后，亮色主题永远显示黑色字体，深色主题永远显示白色字体

### 如何复现问题
同上

### 期望结果
正常显示/识别html语句或哪里可以改相关设置/代码

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
有图吗？不清楚你描述的什么问题

**Comment by Milktea77** [comment]
少打了一句话，html代码里套用加粗【**123456**】时，原来html语法失效

Drake Purple主题下
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/102573319/849649f9-a28d-43db-ac28-c8aff975f592)
原主题下：
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/102573319/9cbff54b-edb6-48a6-870b-f8e2a294fad8)
实测~~的删除线语法和^^的角标语法都没有问题，只有加粗的**会导致颜色失效

**Comment by liangjingkanji** [comment]
已修复

**Comment by Milktea77** [comment]
谢谢 辛苦
