### ISSUE TITLE
请问滚动条的样式是哪个？

### ISSUE THREAD

**Issue by lwr971203** [liangjingkanji/DrakeTyporaTheme#153]
我使用深色款的（drake-purple）看不清滚动条
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/72763631/4f2714e6-9322-4a50-86dd-200735b90934)
麻烦告知一下滚动条的样式是哪个css属性值，我手动改一下颜色

**Comment by liangjingkanji** [comment]
我也不知道是哪个属性

**Comment by liangjingkanji** [comment]
你可以上Typora官网看下怎么查找, 我这边应该没有改过滚动条颜色

**Comment by lwr971203** [comment]
我切换了你的另一个亮色主题，滚动条颜色是不同的，但你的css里确实找不到右侧滚动条的修改记录。
不过我刚刚用::-webkit-scrollbar-thumb强行改了滚动条，有效果了。

**Comment by liangjingkanji** [comment]
> 我切换了你的另一个亮色主题，滚动条颜色是不同的，但你的css里确实找不到右侧滚动条的修改记录。 不过我刚刚用::-webkit-scrollbar-thumb强行改了滚动条，有效果了。

那是因为滚动条区分亮色/暗色主题
