### ISSUE TITLE
能否改变markdown流程图的样式呢

### ISSUE THREAD

**Issue by JiuYou2020** [liangjingkanji/DrakeTyporaTheme#154]
### 描述问题
我想要改变markdown流程图的样式,可以改变吗,例如将下图的改变为黑色线条方框,白色背景
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/102222347/41969bc3-c9b4-4a73-a26e-f10429099424)

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
请提供markdown语法

1. 如果觉得文字不明显我会修改
2. 如果你想在暗色主题展示亮色流程图请自己参考Typora官方文档进行主题编辑
