### ISSUE TITLE
drake-material主题，甘特图底部时间和背景色接近导致看不清

### ISSUE THREAD

**Issue by Lucentio-Huang** [liangjingkanji/DrakeTyporaTheme#155]
### 描述问题
drake-material主题，甘特图底部时间和背景色接近导致看不清

### 如何复现问题
gantt
title 甘特图示例
dateFormat  YYYY-MM-DD
section 项目A    
任务1           :a1, 2023-05-01, 10d    
任务2           :after a1  , 20d
section 项目B    
任务3           :2023-05-15  , 12d    
任务4           :2023-05-20  , 10d

![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/48576858/10e4acaa-abc4-476c-b8dd-bb984da23dc0)

### 期望结果
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/48576858/da06968a-4ec4-4d70-aea8-2d508fb76c39)

### 系统 (建议使用最新Typora版本)
 - OS :windows11
 - Theme :drake-material
 - Typora Version :1.7.6

**Comment by liangjingkanji** [comment]
因为你没升级主题, 下载最新主题使用即可

<img width="1140" alt="image" src="https://github.com/liangjingkanji/DrakeTyporaTheme/assets/21078112/e6a38297-3423-4f08-b832-4ef644a8b3f2">

**Comment by Lucentio-Huang** [comment]
现在就是用2.9.4这个最新版本drake-material这个主题，还是没显示哦，需要在哪里进行设置吗？
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/48576858/e0c9d983-03b0-45ee-a1ec-233ab3243a5e)
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/48576858/f50e745e-20e2-4270-aad1-665bdf95fff9)
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/48576858/598a0aa1-06b0-4c40-a6e2-27dab9a9cae5)

**Comment by liangjingkanji** [comment]
因为最新版本我没发布tag, 现在请使用最新tag:2.9.5, 大部分情况我指的最新版本为主页点击下载
