### ISSUE TITLE
二级标题显示不正确

### ISSUE THREAD

**Issue by voncin** [liangjingkanji/DrakeTyporaTheme#16]
当添加二级标题时会被分成了三行;

```markdown
## 二级标题: `#`+`Space`标记标题
```
![image](https://user-images.githubusercontent.com/68265597/126294912-c70d9003-d1d9-4752-9bd7-0c79cb06c8cf.png)

二级标题不能使用重音符, `丶` ;

**Comment by liangjingkanji** [comment]
好的, 我修复下

**Comment by voncin** [comment]
我自己改了一下:
删掉了:
h2&nbsp;.md-plain:after&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;display:&nbsp;block;
&nbsp;&nbsp;&nbsp;&nbsp;content:&nbsp;'';
&nbsp;&nbsp;&nbsp;&nbsp;height:&nbsp;2px;
&nbsp;&nbsp;&nbsp;&nbsp;margin-top:&nbsp;4px;
&nbsp;&nbsp;&nbsp;&nbsp;background-color:&nbsp;var(--h2-underline-bg);
&nbsp;&nbsp;&nbsp;&nbsp;border-radius:&nbsp;2px;
}
&gt;&gt;
h2&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;font-size:&nbsp;1.6rem;
&nbsp;&nbsp;&nbsp;&nbsp;display:&nbsp;inline-block;
改成这个
&nbsp;&nbsp;&nbsp;&nbsp;padding-bottom:&nbsp;4px;
&nbsp;&nbsp;&nbsp;&nbsp;border-bottom:&nbsp;2px&nbsp;solid&nbsp;var(--h2-underline-bg);
}



&nbsp;

              
             王新意         
         
             手机:+86 171-5516-1089         
         
             邮箱:                              ***@***.***                      
      


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月20日(星期二) 下午5:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liangjingkanji/DrakeTyporaTheme]二级标题显示不正确 (#16)





 
好的, 我修复下

**Comment by liangjingkanji** [comment]
升级比较好, 毕竟一直有更新不清楚你具体什么时候下载的. 还用建议你重新编辑你的评论避免泄露敏感信息
