### ISSUE TITLE
六级标题和五级标题相同

### ISSUE THREAD

**Issue by wxss-0823** [liangjingkanji/DrakeTyporaTheme#160]
### 描述问题
主题 Drake 中，六级标题和五级标题渲染效果相同，无法区分。

### 如何复现问题
输入 `##### 五级标题` 和 `###### 六级标题` ，源码显示正确，单纯渲染结果相同。

### 期望结果
六级标题与五级标题之间存在区别。

### 截图
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/82258843/6f51753b-ab1c-4f00-9f31-17d462ad7d58)
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/82258843/de77fbed-0780-414f-b02f-6a22aa8b8209)

### 系统 (建议使用最新Typora版本)
 - OS Window 11
 - Theme Drake
 - Typora Version 1.8.3-dev

**Comment by liangjingkanji** [comment]
感觉不适合再小了, 标题本身只是为了大纲排版, 如果标题小的和文字区别不大那就没什么含义了吧

**Comment by wxss-0823** [comment]
大小不适合调整的话，可以在颜色深浅，或者透明度上做些文章，至少可以肉眼看出与五级标题的区别就够了，否则这个主题的六级标题就没什么意义了对吗

**Comment by liangjingkanji** [comment]
> 大小不适合调整的话，可以在颜色深浅，或者透明度上做些文章，至少可以肉眼看出与五级标题的区别就够了，否则这个主题的六级标题就没什么意义了对吗

六级标题是大纲排版用, 至于颜色的话, 我不太喜欢太多颜色花里胡哨的

**Comment by liangjingkanji** [comment]
我认为完全靠大小去区分几级标题, 你分得清楚吗? 这是给左侧大纲排版用的

**Comment by liangjingkanji** [comment]
除非你能提供更好的方案说服我, 否则只能自己定制了, 我在主题文件中使用描述方便了一些自定义配置
