### ISSUE TITLE
Vue3主题中左下角"退出源代码模式"按钮显示问题

### ISSUE THREAD

**Issue by 1538-art** [liangjingkanji/DrakeTyporaTheme#161]
### 描述问题

Vue3主题中左下角"退出源代码模式"按钮显得很突出且文字与背景颜色缺乏对比度

### 如何复现问题

在Vue3主题下切换到源代码模式

### 期望结果

希望该按钮变得更符合该主题的风格

### 截图

<img width="145" alt="2024-02-08_09-24-41-0" src="https://github.com/liangjingkanji/DrakeTyporaTheme/assets/85423635/1e7f865a-2c25-47fa-bbf1-ed34e0f1273a">

### 系统 (建议使用最新Typora版本)
 - OS : Windows 11
 - Theme : drake-vue3
 - Typora Version : 1.8.10

**Comment by 1538-art** [comment]
不好意思 版本搞错了 应该是1.8.10

**Comment by Yijiu-github** [comment]
我也出现了同样的问题
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/128239081/e954d009-8fa6-4d55-9ff0-981894cdfe69)

**Comment by liangjingkanji** [comment]
暂不清楚源码模式如何修改颜色

**Comment by liangjingkanji** [comment]
由于这个按钮是Windows特有, 搞了个Windows才修复
