### ISSUE TITLE
设置中有一部分颜色出错，并且无法修改

### ISSUE THREAD

**Issue by obscurefreeman** [liangjingkanji/DrakeTyporaTheme#162]
在我制作自己的主题时，发现设置中一部分颜色固定，无法修改。我发现其他主题也有这个问题，想问问是否有方法解决这个问题。

打开偏好设置栏就可以看到这些问题。

![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/119153032/dcefdb49-7cdc-4da9-b137-9331c56b097c)

### 系统 (建议使用最新Typora版本)
 - Windows 11
 - 所有主题都存在此问题
 - Typora 版本 1.0.3

**Comment by catterdx** [comment]
超链的样式算是与此主题相关https://github.com/liangjingkanji/DrakeTyporaTheme/blob/9e258b7c98cacc2783b27b2b5c14db2ac4007332/drake-ayu.css#L336
但背景色与主题无关, 属于内置的样式, 要主暗系与明亮色系本色相关
.export-detail {
 background: var(xxx);
}

**Comment by liangjingkanji** [comment]
已修复, 你重新下载即可
