### ISSUE TITLE
主题Drake Jb里的问题请教

### ISSUE THREAD

**Issue by 94MJ** [liangjingkanji/DrakeTyporaTheme#165]
### 描述问题
Jb这个主题里的表格样式是显示bug呢，还是这样设计的，没有竖线分割，而且，看起来怪怪的，和Jb本身的设计风格好像有点格格不入？

### 期望结果
请问，如果不是bug，能否告知是css文件里哪部分代码控制的，我自己替换下别的主题里的表格样式

### 截图
![2024-4-5 21-38-45](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/53167202/f82d8e19-a22a-4727-a1c4-d3ed9cc3d541)

### 系统 (建议使用最新Typora版本)
 - OS
windows
 - Theme
 Jb 
 - Typora Version
 1.8.6

**Comment by liangjingkanji** [comment]
因为jb风格表格就是没有竖线

**Comment by liangjingkanji** [comment]
本想截图给你看, 但是没找到好像现在都有竖线了, 不过我觉得没有更有风格
