### ISSUE TITLE
暗黑色主题下图片显示问题

### ISSUE THREAD

**Issue by Mixlining** [liangjingkanji/DrakeTyporaTheme#167]
### 描述问题
在暗黑色主题（本项目下所有暗色主题）下显示图片会出现异常

### 如何复现问题
该图片在主题下显示异常 ：https://gitee.com/jackfrued/mypic/raw/master/20210803201644.png

 （github点击好像不能直接跳转，需要手动复制到浏览器输入）

### 期望结果
能够和白色主题一样正常显示图片

### 截图
[异常图片如图](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/91776353/92e1457f-e0de-4b31-bd0f-1a7558ec693d)

### 系统 (建议使用最新Typora版本)
 - OS windows10
 - Theme 主题下所有暗黑色主题
 - Typora Version 1.8.10

**Comment by liangjingkanji** [comment]
把复现问题的markdown内容贴出来

**Comment by liangjingkanji** [comment]
不明白显示有什么问题, 麻烦截图贴在这里
