### ISSUE TITLE
词数多就会卡顿

### ISSUE THREAD

**Issue by xSeaGull** [liangjingkanji/DrakeTyporaTheme#17]
mac typora 版本0.11.0 (5581)，在快2000词的时候 卡顿明显。虽然使用其他主题也有，但没那么明显

**Comment by liangjingkanji** [comment]
快2000词就卡..... 心理作用吧, 这个主题本身并没有加任何冗余的渲染

你给Typora作者反馈下: https://github.com/typora/typora-issues/issues

**Comment by xSeaGull** [comment]
应该是typora官方问题
