### ISSUE TITLE
H2字体样式, 无法渲染下划线/分界线

### ISSUE THREAD

**Issue by Junru281** [liangjingkanji/DrakeTyporaTheme#174]
### 描述问题
下载主题后打开README.md, Customize (自定义)的H2区域无法显示下划线/ 分界线. 

### 期望结果
<img width="392" alt="Screenshot 2024-10-17 at 12 33 39 PM" src="https://github.com/user-attachments/assets/8a32e029-de5a-4124-a5b5-1ded9cc9ffa7">

### 截图
<img width="549" alt="Screenshot 2024-10-17 at 12 37 57 PM" src="https://github.com/user-attachments/assets/e8e85ba5-580b-431b-be37-f1a8a060395c">

### 系统 (建议使用最新Typora版本)
 - OS
 - MacOS Apple Silicon
 - Theme 
 - Drake vue, Drake Juejin, Drake...
 - Typora Version
 - 0.11.18 和1.8.10

**Comment by lnut220303082** [comment]
我也遇到了这样的问题

**Comment by liangjingkanji** [comment]
二级标题自动下划线效果已经被删了

因为它导致其他问题(具体问题忘记了, 可以issues搜索), 暂时没有能力修复

**Comment by Junru281** [comment]
好的, 了解! 感谢!
