### ISSUE TITLE
关于代码中空格问题

### ISSUE THREAD

**Issue by David-Xia** [liangjingkanji/DrakeTyporaTheme#18]
你好，
    你提供的Typora主题非常好，配色很nice。但我在使用中出现了一个问题，当我插入python代码时，缩进的时候前面有4个空格，每个空格应该占据1个字符长度，4个空格等于一个Tab键，当你的主题下，不是这样的，每个空格占据的不是一个字符长度，也不是半个，总之和上一行的代码没法对齐。我换了Typora自带的theme，没有出现这个问题。

**Comment by liangjingkanji** [comment]
我查看下

**Comment by David-Xia** [comment]
我的操作系统是Ubuntu16.04，这是我用Drake Ayu的Python代码段：
![2021-07-23 11-54-41屏幕截图](https://user-images.githubusercontent.com/23613876/126735873-09ca9025-cf5b-433a-a513-f7afde8a654a.png)
这是我用Typora自带的Night：
![2021-07-23 11-55-04屏幕截图](https://user-images.githubusercontent.com/23613876/126735891-8dac39db-45c1-4d2a-8697-a7a29e2a2dce.png)
我刚才将这一段CSS注释掉就没问题了：
![2021-07-23 12-00-39屏幕截图](https://user-images.githubusercontent.com/23613876/126735941-6de3dafd-38f5-4aa5-86f6-05ab51d9fec3.png)
我不知道是什么原因导致这样的，我的代码缩进也是设置成4。

**Comment by liangjingkanji** [comment]
估计是字体问题, 你按照说明设置成你电脑上已有的字体吧

**Comment by liangjingkanji** [comment]
我也将注释掉这一行, 谢谢你的反馈
