### ISSUE TITLE
可否搞个黑色主题的

### ISSUE THREAD

**Issue by snsyzf** [liangjingkanji/DrakeTyporaTheme#2]

**Comment by liangjingkanji** [comment]
已更新暗色主题, 亮色主题也更加扁平化, 有提议或者问题可以反馈或者pr

![截图](https://raw.githubusercontent.com/liangjingkanji/DrakeTyporaTheme/master/img/thumbnail-dark.png)

**Comment by liangjingkanji** [comment]
![](https://raw.githubusercontent.com/liangjingkanji/DrakeTyporaTheme/master/img/thumbnail-purple.png)

**Comment by liangjingkanji** [comment]
新增 Ayu 风格

![](https://raw.githubusercontent.com/liangjingkanji/DrakeTyporaTheme/master/img/thumbnail-ayu.png)
