### ISSUE TITLE
代码段最后一个行号显示异常

### ISSUE THREAD

**Issue by Xgwb** [liangjingkanji/DrakeTyporaTheme#20]
![Snipaste_2021-08-05_13-39-43](https://user-images.githubusercontent.com/21021644/128297131-d855632b-1e14-4e55-bc11-d963e4384f0d.png)

每个代码段后面都有一块灰色遮罩

**Comment by liangjingkanji** [comment]
我这里并无此问题, 请问你是Windows是吗?

**Comment by Xgwb** [comment]
系统：Windows 10
主题：Drake Light
Typora：0.11.2

**Comment by Xgwb** [comment]
![Snipaste_2021-08-05_13-50-14](https://user-images.githubusercontent.com/21021644/128298120-a8f8aa15-3176-4f6f-a10a-04be8ce1024c.png)
调试发现，是因为这个样式导致的
