### ISSUE TITLE
使用 Drake Light 主题，导致 “菜单” --> "打开" 选项中样式出问题

### ISSUE THREAD

**Issue by Xgwb** [liangjingkanji/DrakeTyporaTheme#21]
### 描述问题
如题

### 如何复现问题
切换到 `Drake` 主题，100% 复现

### 截图
![Snipaste_2021-08-05_14-22-11](https://user-images.githubusercontent.com/21021644/128301655-706d8ded-ba84-4553-b352-6b3cdf4b8a05.png)
以上是使用 `官方 Github` 主题时，菜单样式

![Snipaste_2021-08-05_14-22-28](https://user-images.githubusercontent.com/21021644/128301717-9af0ec08-96ae-4f00-9c3a-5d16e9dc2be7.png)
以上是切换到 `Drake Light` 主题，菜单样式，会发现 `打开`、`导入` 位置错乱

### 系统 (please complete the following information):
 - OS: WIndows
 - 风格 Drake Ligth
 - Typora版本 0.11.2

**Comment by liangjingkanji** [comment]
这个界面怎么打开的?

**Comment by Xgwb** [comment]
偏好设置 --> 外观 --> 窗口样式 选择一体化

**Comment by liangjingkanji** [comment]
记得重新下载主题
