### ISSUE TITLE
Ayu 主题 大菜单界面显示异常

### ISSUE THREAD

**Issue by sonderlau** [liangjingkanji/DrakeTyporaTheme#27]
### 描述问题

Windows 下使用 Drake-Ayu 主题
在大菜单界面颜色未设置

### 截图

![image](https://user-images.githubusercontent.com/12829325/130258222-409aaac6-4eae-4f41-a3a7-461febaf3e8e.png)

### 系统 (首先建议使用最新Typora版本):
 - OS: [e.g. macOS] Windows 11
 - 风格 [e.g. drake, ayu]  ayu
 - Typora版本 [e.g. 22]  0.11.5

**Comment by liangjingkanji** [comment]
稍等, 我查看下你的PR以及在Windows复现下问题

**Comment by sonderlau** [comment]
> 关于windows的这个界面我需要为所有风格重新设计下, 今天会修复完毕.

这个问题在Typora Gallery上几乎任何一个非官方的主题都会出现
Windows群体饱受折磨…

**Comment by liangjingkanji** [comment]
我懂折磨点, 细节很重要, 不然就像眼睛里面的沙子. 我会针对每个风格重新适配这个界面的. 包括light风格

**Comment by liangjingkanji** [comment]
![image](https://user-images.githubusercontent.com/21078112/130292212-2965299f-b303-4603-9a88-d7d7a81240f5.png)

已经为所有主题适配一体化界面
