### ISSUE TITLE
drake主题 代码块中的光标不明显

### ISSUE THREAD

**Issue by lvlvforever** [liangjingkanji/DrakeTyporaTheme#29]
### 描述问题
drake主题 代码块中的光标不明显
### 如何复现问题
使用shell格式的代码块，查看光标

### 期望结果
希望光标颜色与背景进行区分
### 截图
![image](https://user-images.githubusercontent.com/13757893/130260716-b65d51b3-cae6-4b1e-aa23-04913dc13e4e.png)

### 系统 (首先建议使用最新Typora版本):
 - OS: [e.g. macOS] macos
 - 风格 [e.g. drake, ayu] drake 
 - Typora版本 [e.g. 22] 0.11.5 

### 问题解决
 我通过修改drake.css里的属性解决。
具体是使用 border-left: 2px solid #ff8080 !important;
替换掉drake.css中的
.cm-s-inner div.CodeMirror-cursor和.cm-s-inner .CodeMirror-cursor类里的相应属性
如下图
![image](https://user-images.githubusercontent.com/13757893/130261139-21a2c6c5-d6c1-4565-854b-d4ad63c4e4a8.png)

**Comment by liangjingkanji** [comment]
好的我修复提交
