### ISSUE TITLE
中文和英文之间加空格，显示过宽，这个如何修改？

### ISSUE THREAD

**Issue by longhaiqwe** [liangjingkanji/DrakeTyporaTheme#3]
我相信大家都已经习惯在中英文之间敲个空格，但是我们这个主题，空格显示太宽了：
![image](https://user-images.githubusercontent.com/6258657/100059693-71758080-2e66-11eb-928e-ecdb3583f43e.png)

**Comment by longhaiqwe** [comment]
好像是字体的原因，JetBrains Mono 的空格就是比较宽。

**Comment by longhaiqwe** [comment]
好像是字体的原因，JetBrains Mono 的空格就是比较宽。

**Comment by liangjingkanji** [comment]
这个无法做到, 不过你可以根据文档替换掉字体

**Comment by longhaiqwe** [comment]
> 这个无法做到, 不过你可以根据文档替换掉字体

是的，我发现就是字体原因 💯
