### ISSUE TITLE
Ayu 在 == == 高亮语法下颜色显示异常

### ISSUE THREAD

**Issue by sonderlau** [liangjingkanji/DrakeTyporaTheme#30]
### 描述问题

`==Markup==` 语法在 `dark-ayu` 布局下显示异常

### 截图
![image](https://user-images.githubusercontent.com/12829325/130307079-bdca0c00-cfd7-41a2-a78c-a143fc2a9edc.png)

### 系统 (首先建议使用最新Typora版本):
 - OS: [e.g. macOS] Windows 11
 - 风格 [e.g. drake, ayu] ayu
 - Typora版本 [e.g. 22]  0.11.5

修改如下代码段即可
![image](https://user-images.githubusercontent.com/12829325/130307105-400718fd-b91a-4677-ba77-0090cdc92d7d.png)

**Comment by liangjingkanji** [comment]
稍等我更新

**Comment by liangjingkanji** [comment]
我记起来了高亮语法好像Typora已经删了吧?
