### ISSUE TITLE
<kbd>标签显示异常

### ISSUE THREAD

**Issue by sonderlau** [liangjingkanji/DrakeTyporaTheme#31]
### 描述问题
在 Markdown 中使用 `<kbd>` 标签 配色为默认的配色

### 截图
![image](https://user-images.githubusercontent.com/12829325/130341846-dbe971db-6d10-4b78-ad22-65a3837494e2.png)
![image](https://user-images.githubusercontent.com/12829325/130341849-97bd9f70-36a7-4ada-94ad-e31c9f2a0251.png)

### 系统 (建议使用最新Typora版本)
 - OS Windows11
 - Theme  **Ayu**
 - Typora Version 0.11.5

**Comment by liangjingkanji** [comment]
已添加kbd样式

![image](https://user-images.githubusercontent.com/21078112/130346027-bd1534ef-ae64-4216-96a0-c6871eec8d56.png)
![image](https://user-images.githubusercontent.com/21078112/130346044-2ae291a5-4095-4af3-af16-b9388776773c.png)
