### ISSUE TITLE
Light Vue主题 加粗显示不明显

### ISSUE THREAD

**Issue by sonderlau** [liangjingkanji/DrakeTyporaTheme#32]
### 截图

![image](https://user-images.githubusercontent.com/12829325/130991480-c9090344-d532-4cf8-9359-775a51f99e7a.png)
![image](https://user-images.githubusercontent.com/12829325/130991648-5244de46-00bf-45cf-9800-8fb9458cc244.png)

### 系统 (建议使用最新Typora版本)
 - OS Windows 11
 - Theme  Light and Vue
 - Typora Version 0.11.6

**Comment by liangjingkanji** [comment]
提高暗色模式的标题/粗体颜色亮度, 提升和普通文本对比度
