### ISSUE TITLE
调整字体大小

### ISSUE THREAD

**Issue by qidanei624** [liangjingkanji/DrakeTyporaTheme#33]
### 描述问题
win7  正文字体 12px 太小了， 代码字体大小12px还可以

作者的 mac系统显示不小吗？ 整体配色挺好看的，这几天一直用这个主题，谢谢分享啊！！

**Comment by liangjingkanji** [comment]
关于字体大小你可以在设置界面设置, 不使用`自动`即可

![image](https://user-images.githubusercontent.com/21078112/131225098-aa858196-8d69-480e-86e2-cfa14c05d8f8.png)

![image](https://user-images.githubusercontent.com/21078112/131225124-f51ccf14-8093-4dd0-a42f-52680cede82c.png)
