### ISSUE TITLE
为啥我的typora渲染不出圆角(没有高亮语法效果)

### ISSUE THREAD

**Issue by Ryutaku** [liangjingkanji/DrakeTyporaTheme#35]
### 描述问题
主题附带的效果图中“本主题可根据全局属性定制字体/配色”是用圆角包进来的，为啥我引用了Drake主题后，无此效果。

直接打开主题附带的README.MD文件后，确实无法正常渲染出此效果。

### 截图

![image](https://user-images.githubusercontent.com/1673177/133230906-5c13165b-d515-4eed-a5aa-13fbf7aba167.png)

### 系统 (建议使用最新Typora版本)
 - OS
 Windows 11
 - Theme 
 Drake Vue
 - Typora Version
 0.11.8

**Comment by liangjingkanji** [comment]
因为高亮这个效果在很多Markdown编辑器中是不支持的, 所以Typora官方默认禁止此效果

请你去设置界面手动打开

![image](https://user-images.githubusercontent.com/21078112/133241225-754c8eaa-2edf-4af8-9d72-9043f3d4513a.png)

**Comment by Ryutaku** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        OK
        谢谢.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ryutaku
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年9月14日 ***@***.***> 写道： 




因为高亮这个效果在很多Markdown编辑器中是不支持的, 所以Typora官方默认禁止此效果

请你去设置界面手动打开





—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ryutaku** [comment]
**OK，谢谢**
