### ISSUE TITLE
标题提醒

### ISSUE THREAD

**Issue by andyRon** [liangjingkanji/DrakeTyporaTheme#36]
不是问题，就一个建议！
光标在标题上时，能否动态显示是几号标题？
当文档比较长时，标题比较多时，有时到`<h5>`，`<h6>`时，只凭字体大小很难区分

类似这样的：
![](https://user-images.githubusercontent.com/6138495/133707419-07f33aec-efe4-4160-8cd5-40fe85a960b0.jpg)

**Comment by liangjingkanji** [comment]
**大纲才是用来查看标题层级的**

标题主要是用来构建目录结构
这种光标在上才显示目录序号, 意义不大. 就算直到当前是四级标题, 你上一个标题能看到吗? 或者看到你能知道几级标题吗?

可以的话希望你能阐述看到标题序号的优势

<img src="https://user-images.githubusercontent.com/21078112/133714359-f9dcfafc-66e9-40c8-b6d3-4144c88555ac.png" width="30%"/>
