### ISSUE TITLE
打开readme后kbd语法中的字体和主页中截图的字体不一样

### ISSUE THREAD

**Issue by Yuteng-Zhang** [liangjingkanji/DrakeTyporaTheme#37]
### 描述问题
打开readme后kbd语法中的字体和主页中截图的字体不一样

### 期望结果
主页截图
![image](https://user-images.githubusercontent.com/71632214/135238156-df97e273-369d-4fff-b839-8f99715b7e05.png)

### 截图
使用截图
![image](https://user-images.githubusercontent.com/71632214/135238050-c80550ca-47a5-4f40-b0ea-0bb86b182ec0.png)

### 系统 (建议使用最新Typora版本)
 - OS Windows
 - Theme drake 2.7
 - Typora Version 0.9.98

**Comment by liangjingkanji** [comment]
截图字体是: "JetBrains Mono", HYZhengYuan

你有安装吗?

**Comment by Yuteng-Zhang** [comment]
都安装啦

**Comment by Yuteng-Zhang** [comment]
已找到原因，是因为typora的语言设置为跟随系统（英文），后把typora改成中文，字体就和主页的截图一样了

**Comment by liangjingkanji** [comment]
主页我已经添加下载地址: 
```
预览截图字体: 英文 JetBrains Mono, 中文 HYZhengYuan 安装方可有预览字体效果
```

英文难道不会使用设置的字体么, 真奇怪呢

**Comment by Yuteng-Zhang** [comment]
仅截图这块非正常，其他的字体在typora英文下都是正常的

**Comment by liangjingkanji** [comment]
主题并没有对kbd单独设置字体, 真奇怪呢, 解决就行
