### ISSUE TITLE
二级标题显示错误

### ISSUE THREAD

**Issue by secriy** [liangjingkanji/DrakeTyporaTheme#38]
### 描述问题

多个没有正文内容的二级标题会显示在一行中。尝试过其他主题不存在该问题。仅有二级标题存在该问题。

### 如何复现问题

创建多个连在一起的二级标题。

### 期望结果

多个标题换行显示。

### 截图

![image](https://user-images.githubusercontent.com/41107263/135820201-ed096cb6-f097-455a-a4ac-a96a04a01aa2.png)

![image](https://user-images.githubusercontent.com/41107263/135820236-adc747f7-c5e2-4d3b-811c-077429cf8254.png)

### 系统

 - Windows 10
 - Drake 所有主题
 - Typora 0.11.8

**Comment by liangjingkanji** [comment]
你使用回车键换行下，这个是为了实现下划线所以才有的问题
