### ISSUE TITLE
请问截图内的中文字体是怎么设置的

### ISSUE THREAD

**Issue by oriofdarkforest** [liangjingkanji/DrakeTyporaTheme#4]
windows用户选用了这个主题, 中文还是宋体的

**Comment by liangjingkanji** [comment]
JetBrains Mono 不支持中文,  如果你需要支持自己独有的中文字体, 可以修改
`"JetBrains Mono"`  改成 `"JetBrains Mono", "自己的中文字体名称"` 就可以修改中文字体了

**Comment by liangjingkanji** [comment]
![image](https://user-images.githubusercontent.com/21078112/102457358-97fd9480-407d-11eb-9145-aeb03feb672e.png)
