### ISSUE TITLE
怎么修改任务列表的颜色

### ISSUE THREAD

**Issue by Imane219** [liangjingkanji/DrakeTyporaTheme#41]
### 描述问题
任务列表的颜色是绿色，该如何修改css代码来变换颜色呢？

### 截图
![image](https://user-images.githubusercontent.com/48405078/140712692-1f2fdba8-1201-4608-a5ab-b7471e749653.png)

### 系统 (建议使用最新Typora版本)
 - OS : win10
 - Theme : drake
 - Typora Version : 0.9.98

**Comment by liangjingkanji** [comment]
修改css文件里面的两个属性
- --checkbox-checked 选中
- --checkbox-unchecked 未选中

值为矢量图标

**Comment by Imane219** [comment]
> 修改css文件里面的两个属性
> 
> * --checkbox-checked 选中
> * --checkbox-unchecked 未选中
> 
> 值为矢量图标. 如果仅仅是修改颜色请修改其原有值的`fill='%2365b73b'`, 其中`65b73b`就是16进制颜色值

已解决，谢谢！
那么应该如何改变无序列表的行距呢？

**Comment by liangjingkanji** [comment]
```
blockquote,
ul,
ol,
dl,
table {
    margin: 0.8em 0; /*行间距*/
}
```
