### ISSUE TITLE
请问怎样调整正文的左右边距

### ISSUE THREAD

**Issue by fsafaf** [liangjingkanji/DrakeTyporaTheme#42]
### 描述问题
想知道怎样调整显示正文内容的的左右边距，让两边的空白少一点

### 截图
<img width="1828" alt="iShot2021-11-27 05 09 28" src="https://user-images.githubusercontent.com/47275775/143651223-86a28643-3c0f-4417-a107-047be6dad425.png">

### 系统 (建议使用最新Typora版本)
 - OS Mac OS 12.1
 - Theme drake-light
 - Typora Version 1.0.2 (5990)

**Comment by liangjingkanji** [comment]
找到`186行`的`#write {`

修改`max-width: 1200px;` 为 `max-width: 100%;` 即可

**Comment by fsafaf** [comment]
> 找到`186行`的`#write {`
> 
> 修改`max-width: 1200px;` 为 `max-width: 100%;` 即可

已经解决了，非常感谢

**Comment by liangjingkanji** [comment]
喜欢就行
