### ISSUE TITLE
黑色主题Markdown绘制的时序图文字颜色bug

### ISSUE THREAD

**Issue by dongbingliu** [liangjingkanji/DrakeTyporaTheme#44]
### 描述问题
黑色主题Markdown绘制的时序图文字颜色bug

### 如何复现问题
测试代码
```mermaid
sequenceDiagram
autonumber
participant A as 业务前端
participant B as 业务后端
participant C as test前端
participant D as test后端
participant E as test系统
A->>B: 下单请求
B->>D: 请求下单接口，创建订单
D-->>B: 返回订单信息
B-->>A: 返回订单信息
A->>C: 调起PC支付页面
C->>C: 用户确认支付
C->>D: 1内部支付逻辑
alt 如果购买的是代币物品
D->>D: 1内部发货
else 如果购买的是月卡物品
D->>D: 1内部发货
else 如果购买的是道具物品
D->>B: 通知发货
B-->>D: 发货回调
else 如果购买的是1物品
D->>E: 通知发货
E->>B: 通知发货
B-->>E: 发货回调
E-->>D: 发货回调
end
D-->>C: 支付结果
C-->>A: 前端回调
alt 如果购买的是代币物品
A->>B: 查询代币余额
B->>D: 查询代币余额
D-->>B: 返回代币余额
B-->>A: 返回代币余额
else 如果购买的是月卡物品
A->>B: 查询月卡
B->>D: 查询月卡
D-->>B: 返回结果
B-->>A: 返回结果
else 如果购买的是道具物品
A->>B: 查询物品
B-->>A: 返回结果
else 如果购买的是1物品
A->>B: 查询物品
B-->>A: 返回结果
end
```

### 期望结果
背景黑色, 文字与箭头期望白色

### 截图
![image](https://user-images.githubusercontent.com/7981299/144196054-35096187-3cee-4ff7-b399-fd19f9733415.png)

### 系统 (建议使用最新Typora版本)
 - OS Windows
 - Theme  DrakeDark
 - Typora Version 1.0.2

**Comment by liangjingkanji** [comment]
没写过时序图, 我尝试修复下

**Comment by liangjingkanji** [comment]
你这个示例代码我粘贴到Typora不显示时序图

**Comment by liangjingkanji** [comment]
时序图可以修改样式, 但是一旦编辑时序图代码马上会显示默认的样式(不会读取主题时序图css), 这属于typora的bug了

所以我暂时只兼容了默认的时序图暗色模式. 如果想要更漂亮的时序图请向typora作者反馈这个问题

**Comment by dongbingliu** [comment]
修复问题真及时 , 非常感谢

typora 里面用了很多主题就你强哥主题最Nice,现代化,  种类还多

**Comment by liangjingkanji** [comment]
也不是很及时, 以前有问题都是当天内就修复了

本来还是想修改时序图样式, 结果typora有bug. 有空我得跟作者反馈下

**Comment by liangjingkanji** [comment]
- 新增时序图样式

<img src="https://user-images.githubusercontent.com/21078112/144546112-39f628fd-f325-4d85-82d9-9a542ae1a725.png" width="30%"/><img src="https://user-images.githubusercontent.com/21078112/144546134-22f5493a-0168-415c-a122-183b4a0bbf2d.png" width="30%"/>
