### ISSUE TITLE
需要自己下载字体吗

### ISSUE THREAD

**Issue by azeng233** [liangjingkanji/DrakeTyporaTheme#45]
### 描述问题
使用主题后发现字体并不是mono，是需要自己下载字体吗

### 系统 (建议使用最新Typora版本)
 - Windows
 - drake-light
 - Typora Version latest

**Comment by liangjingkanji** [comment]
对, 需要自己安装

**Comment by azeng233** [comment]
谢谢

**Comment by liangjingkanji** [comment]
已经更新预装字体, 感觉可能体验比较好

**Comment by azeng233** [comment]
> 已经更新预装字体, 感觉可能体验比较好

是HYZhengYi这个字体吗🎡

**Comment by liangjingkanji** [comment]
drake目录下都是字体. 主题里面也引用了字体
