### ISSUE TITLE
当打开 Drake Material 以及专注模式时非专注的行更明显。

### ISSUE THREAD

**Issue by Cubik65536** [liangjingkanji/DrakeTyporaTheme#46]
### 描述问题
当打开 Drake Material 以及专注模式时，当前行相对于其它行更暗，比较难以看清。

> 其他深色模式的主题也有类似问题

### 如何复现问题
1. 使用 Drake Material 主题
2. 打开专注模式

### 期望结果
当前行更亮，其它行更暗

### 截图
<img width="996" alt="iShot2021-12-05 20 51 23" src="https://user-images.githubusercontent.com/72877496/144774813-e9ae934e-93ae-4fc4-8410-6893aad4fe10.png">

### 系统 (建议使用最新Typora版本)
 - OS：macOS Monterey Version 12.0.1 (21A559)
 - Theme: Drake Material
 - Typora Version: Version 1.0.2 (5990)

**Comment by liangjingkanji** [comment]
稍等我修复下, 当然你也可以修复👾

**Comment by Cubik65536** [comment]
> 稍等我修复下, 当然你也可以修复👾

我试着按照 [官方文档](https://support.typora.io/Change-Styles-in-Focus-Mode/) 更改CSS并未成功

**Comment by liangjingkanji** [comment]
不错, 那等我修复下

**Comment by liangjingkanji** [comment]
已修复专注模式, 你下载试试

**Comment by Cubik65536** [comment]
> 已修复专注模式, 你下载试试

已经可以正常使用，感谢！

**Comment by liangjingkanji** [comment]
非专注模式下二级标题下划线颜色出现问题了, 我又修复了下
