### ISSUE TITLE
单纯发表对这个主题的喜爱

### ISSUE THREAD

**Issue by ioiioo** [liangjingkanji/DrakeTyporaTheme#47]
### 描述问题
单纯发表对这个主题的喜爱, 作者发布的主题真是精品, 匠心之作,细节深得人心. 特别喜欢
1. 喜欢文档内容宽屏展示,不是很窄的居中. 
2. 喜欢字体大小错落有致. 不同级别的内容显示差异明显.整篇文章通过段落可以很好的区分
3. 喜欢行内代码的背景现在这样恰到好处,不那么明显与突出.
4. 喜欢整个风格统一, 背景与文字融入一体.

大大的赞.谢谢作者无私分享.
👍 

### 系统 (建议使用最新Typora版本)
 - OS: macOS 12.1
 - Theme : DrakeTyporaTheme_ALL
 - Typora Version : 0.11.18

**Comment by liangjingkanji** [comment]
o(*≧▽≦)ツ 大家都是作者

**Comment by exposir** [comment]
> 大家都是作者之一. 欢迎你也参与编辑 在我心目中这也是typora最好的主题

支持东哥

**Comment by ZombieBrand** [comment]
确实不错～

**Comment by dongbingliu** [comment]
支持东哥....

**Comment by willzhqiang** [comment]
支持，我也很喜欢，确实精品

**Comment by TransformersWsz** [comment]
谢谢你，东哥:stuck_out_tongue_closed_eyes::stuck_out_tongue_closed_eyes::stuck_out_tongue_closed_eyes:

**Comment by TransformersWsz** [comment]
> 谢谢你，东哥😝😝😝

我点的这个star正好凑满一千:laughing:

**Comment by liangjingkanji** [comment]
> > 谢谢你，东哥😝😝😝
> 
> 我点的这个star正好凑满一千😆

那有空再新增个主题style庆祝下

**Comment by MkBk113** [comment]
一眼就喜欢上这个主题

**Comment by GWrety** [comment]
真的好看，谢谢你

**Comment by FrederickAsYou** [comment]
根本没法和其他比

**Comment by 87zrjojo** [comment]
这个主题非常好看，怎么好久没更新了，目前感觉字体小了点可否增大一号字显示，大纲可否如果能支持折叠显示和导出html显示（如mdtht这个主题的功能）就好了。
