### ISSUE TITLE
关于段与段正文文字之间没有间隔的问题

### ISSUE THREAD

**Issue by sxlong0205** [liangjingkanji/DrakeTyporaTheme#48]
### 描述问题
默认GitHub主题下，两段文字之间的段间距是要略大于行间距的，这样会让人一目了然的看到哪些文字是一段文字，哪些文字是两段文字。而在该drake google主题中，正文文字的段间距和行间距相同，逼死强迫症。

### 期望结果
能够加大段间距

### 截图

![image](https://user-images.githubusercontent.com/40346828/147398902-b62f7ccd-b603-4034-aa02-4f03fa3af906.png)

### 系统 (建议使用最新Typora版本)
 - OS macOS12.1
 - Theme darke google
 - Typora Version 1.0.5

**Comment by liangjingkanji** [comment]
因为Typora默认的行为是 
<kbd>Shift + 回车</kbd> 换行
<kbd>回车</kbd> 段落

我觉得回车应该为换行, 所以取消了. 我建议你段落使用空一行来表示

**Comment by liangjingkanji** [comment]
刚才我考虑到了可能你的内容是复制粘贴的, 粘贴内容包含段落的确会出现一样的问题

**Comment by sxlong0205** [comment]
感谢回复，我是去试试

**Comment by liangjingkanji** [comment]
为了兼容复制粘贴内容的段落格式. 我决定删除这个特性. 也就是退回到你要求的效果

**Comment by liangjingkanji** [comment]
已改好, 你重新下载就好了

**Comment by sxlong0205** [comment]
好的谢谢
