### ISSUE TITLE
时序图 Object 字体上下居中

### ISSUE THREAD

**Issue by dongbingliu** [liangjingkanji/DrakeTyporaTheme#49]
### 描述问题
时序图 Object 字体上下居中

### 如何复现问题
![image](https://user-images.githubusercontent.com/7981299/147638277-6c3e4b42-1ffc-4954-a883-3407c44f9e7e.png)

### 期望结果
字体上下居中

### 截图
![image](https://user-images.githubusercontent.com/7981299/147638288-212f2a7e-c448-46e5-a606-35fa38fc8fa0.png)

### 系统 (建议使用最新Typora版本)
 - OS : MacOS 
 - Theme 
 - Typora Version

**Comment by dongbingliu** [comment]
期望 Object 主题的字体加粗或者大些, 上下对齐

**Comment by liangjingkanji** [comment]
你查看官方默认的github主题, 我看也是没有对齐的

**Comment by dongbingliu** [comment]
刚确认了, 是没有上下对齐

**Comment by liangjingkanji** [comment]
你给typora作者反馈下, 因为他自动生成的我暂时没啥好办法对齐

另外我把字体再加大会导致未对齐更明显

**Comment by dongbingliu** [comment]
好的, 感谢
