### ISSUE TITLE
代码块中的注释对不齐

### ISSUE THREAD

**Issue by trouble-r** [liangjingkanji/DrakeTyporaTheme#5]
代码块中的注释（写在代码后面的注释，非独立行注释）在源代码模式中是对齐的，在github主题中也是对齐的，但是在您的主题预览中却是无法对齐。

**Comment by liangjingkanji** [comment]
截对比图给我看下，没懂你的对齐含义

**Comment by trouble-r** [comment]
第一张图片为您的主题，第二张为源代码模式，第三张为Github主题，虽然影响不大，但强迫症看了是真难受






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liangjingkanji/DrakeTyporaTheme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月20日(星期天) 下午2:34
收件人:&nbsp;"liangjingkanji/DrakeTyporaTheme"<DrakeTyporaTheme@noreply.github.com&gt;;
抄送:&nbsp;"梁卓鹏"<1677978155@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liangjingkanji/DrakeTyporaTheme] 代码块中的注释对不齐 (#5)





 
截对比图给我看下，没懂你的对齐含义

**Comment by liangjingkanji** [comment]
图在哪?没看到诶

**Comment by trouble-r** [comment]
我放正文里了，这次用附件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liangjingkanji/DrakeTyporaTheme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月20日(星期天) 晚上6:13
收件人:&nbsp;"liangjingkanji/DrakeTyporaTheme"<DrakeTyporaTheme@noreply.github.com&gt;;
抄送:&nbsp;"modest_zp"<1677978155@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liangjingkanji/DrakeTyporaTheme] 代码块中的注释对不齐 (#5)





 
图在哪?没看到诶

**Comment by liangjingkanji** [comment]
你通过邮件回复GitHub issues 要么使用markdown语法要么就到GitHub网站回复, 否则我无法看到图片的,   GitHub转发邮件不会转发附件

**Comment by trouble-r** [comment]
![1](https://user-images.githubusercontent.com/65894668/102713633-a4dfe980-4304-11eb-93f1-3fa0d2562eed.png)
![2](https://user-images.githubusercontent.com/65894668/102713634-a6a9ad00-4304-11eb-9d22-24a115c0795d.png)
![3](https://user-images.githubusercontent.com/65894668/102713636-a7dada00-4304-11eb-8da2-3c9f376ee58b.png)

**Comment by liangjingkanji** [comment]
https://user-images.githubusercontent.com/21078112/102713920-719e5a00-4306-11eb-9d65-66075c489820.mov

我没问题

**Comment by liangjingkanji** [comment]
也许是你是要空格和TAB制表符混用的原因

**Comment by trouble-r** [comment]
https://user-images.githubusercontent.com/65894668/102714129-9a731f00-4307-11eb-8341-a87e82508f05.mp4

**Comment by liangjingkanji** [comment]
你在预览模式下给我手写个注释录屏看下, Typora我没有修改缩进相关代码, 只是修改的CSS色值, 理论说不存在这个BUG啊
