### ISSUE TITLE
mermaid时序图sequenceDiagram

### ISSUE THREAD

**Issue by xixici** [liangjingkanji/DrakeTyporaTheme#51]
### 描述问题
mermaid时序图sequenceDiagram，中间的线会穿过生命周期

### 如何复现问题
sequenceDiagram
    title: 时序图例子
    Alice->>Alice: 自言自语
    Alice->>John: Hello John, how are you?
    %% over 可用于单独一个角色上，也可以用于相邻两个角色间：
    Note over Alice,John: A typical interaction
    %% loop 后跟循环体说明文字
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts!
    John-->>Alice: Great!
    John->>Bob: How about you?
    %% 控制焦点：用来表示时序图中对象执行某个操作的一段时间
    %% activate 角色名 表示**控制焦点
    activate Bob 
    Bob-->>John: Jolly good!
    %% deactivate 角色名 表示控制焦点结束
    deactivate Bob
    Alice->>+Bob: Hello John, how are you?
    rect rgb(175, 255, 212)
    alt is sick
    Bob-->>Alice: Not so good :(
    else is well
    Bob-->>Alice: Feeling fresh like a daisy
    end
    opt Extra response
    Bob-->>Alice: Thanks for asking
    end
    end
    loop communicating
        Alice->>+John: asking some questions
        John-->>-Alice: answer 
    end
    par Alice to John
      Alice->>John: Bye
    and Alice to Bob
      Alice->>Bob: Bye
    end
    Alice-xJohn: 这是一个异步调用
    Alice--xBob: 这是一个异步调用

### 截图
![image](https://user-images.githubusercontent.com/11867924/149936466-41621f67-2364-46dc-88dd-4e596a82e664.png)

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version

**Comment by xixici** [comment]
![image](https://user-images.githubusercontent.com/11867924/149936703-8a5d9997-eeb3-4cfe-b4f8-b01f4a56c0e4.png)
期望

**Comment by liangjingkanji** [comment]
我觉得单纯白色不够明显但是黑色又太明显故意设计成透明的
那我改成不透明浅灰色如何

**Comment by xixici** [comment]
设计这样的原因我不揣测，但有一些主题是正常展示的。
按我的理解，线不能穿过柱子，才符合uml标准

**Comment by liangjingkanji** [comment]
那等我改成灰色

**Comment by liangjingkanji** [comment]
已经修改, 并且同时修复标题颜色和暗色模式下的绿色方块显示
