### ISSUE TITLE
R代码渲染之后，"<-"会变成箭头

### ISSUE THREAD

**Issue by qizhengyang2017** [liangjingkanji/DrakeTyporaTheme#54]
### 描述问题
我用markdown记录数据分析时的一些代码片段。记录R语言代码的时候，赋值操作符"<-"会自动转成箭头

### 如何复现问题
可以输入以下代码
```R
p <- ggplot(e1[[1]],aes(genotype,exp)) + geom_violin(aes(fill=genotype)) + geom_boxplot(width=0.1) +
        ylab('log1p(FPKM)') + xlab(eqtl) + theme_classic() + myfont + scale_fill_manual(values=col[2:1]) +
        scale_x_discrete(labels = c(e1[[2]],e2[[3]])) + xlab(eqtl) + ggtitle(paste0('P =',e1[[4]]))

p
```

### 期望结果
"<-"这个符号不改变

### 截图
![image](https://user-images.githubusercontent.com/27215125/151285447-7479088b-e63b-4335-831b-0ccf85559b78.png)

### 系统 (建议使用最新Typora版本)
 - OS：macOS 12.1
 - Theme： 所有的drake主题
 - Typora Version：1.0.5（6032）

**Comment by liangjingkanji** [comment]
这是自带的字体 JetBrains Mono 的`连字特性`. 和语言无关

你可以去下载不带连字特性的[JetBrains Mono](https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.242)字体(NL结尾就是不带连字特性的), 或者使用其他字体

**Comment by qizhengyang2017** [comment]
请问是把主题目录里的这些文件替换掉就可以了吗?
![image](https://user-images.githubusercontent.com/27215125/151352842-245ec050-a467-49f3-ba51-7ba5609bf0e7.png)

**Comment by liangjingkanji** [comment]
你直接安装字体即可. 不需要修改文件

**Comment by qizhengyang2017** [comment]
字体我安装好了，但重启之后还是原来的样子，是不是需要改css文件？
![image](https://user-images.githubusercontent.com/27215125/151355243-72c9249f-c772-439a-8beb-0d658f715148.png)
![image](https://user-images.githubusercontent.com/27215125/151355281-9abf2a5b-ff9d-4005-ad17-5c16e3a49219.png)

**Comment by qizhengyang2017** [comment]
可以了，每个主题的css文件下的字体改了一下。谢谢！

**Comment by thissuper** [comment]
@liangjingkanji 
安装了，但重启没生效呀，所以还是要修改一下 css？有点麻烦呀...

**Comment by liangjingkanji** [comment]
> @liangjingkanji 安装了，但重启没生效呀，所以还是要修改一下 css？有点麻烦呀...

那改为优先选择`JetBrainsMonoNL`字体版本吧, 虽然我是不能理解为什么有人不喜欢连字

**Comment by thissuper** [comment]
> > @liangjingkanji 安装了，但重启没生效呀，所以还是要修改一下 css？有点麻烦呀...
> 
> 那改为优先选择`JetBrainsMonoNL`字体版本吧, 虽然我是不能理解为什么有人不喜欢连字

看着很别扭😂

**Comment by liangjingkanji** [comment]
> @liangjingkanji 安装了，但重启没生效呀，所以还是要修改一下 css？有点麻烦呀...

好了我替你改了, 更新下主题安装JetBrainsMonoNL字体即可
