### ISSUE TITLE
文件名与图标无法对齐

### ISSUE THREAD

**Issue by pjpjp219** [liangjingkanji/DrakeTyporaTheme#60]
### 描述问题
文件名与图标无法对齐

### 如何复现问题
![image](https://user-images.githubusercontent.com/43691384/152904035-6518f7c5-66ca-4347-9e62-223a303ba5b8.png)

### 期望结果
我自己加了个属性，就对齐了
![image](https://user-images.githubusercontent.com/43691384/152904075-22b94620-e106-4935-b7b5-99976cb6de22.png)

### 截图
在上面

### 系统 (建议使用最新Typora版本)
 - OS  Windows
 - Theme  Drake-Vue
 - Typora Version 最后一个测试版本

**Comment by liangjingkanji** [comment]
你这样调整字体大小后还是会不对齐吧?

**Comment by pjpjp219** [comment]
原来是我修改了字体大小的原因，那有没有什么办法可以解决这个问题呢

**Comment by pjpjp219** [comment]
> 你这样调整字体大小后还是会不对齐吧?

原来是我修改了字体大小的原因，那有没有什么办法可以解决这个问题呢

**Comment by liangjingkanji** [comment]
那我把这个地方字体锁死14px如何(官方主题即如此). 
或者你可以给官方建议调整这块的布局

**Comment by pjpjp219** [comment]
> 
我觉得可行！就是调整编辑器内的字体不应该影响到菜单栏？

**Comment by liangjingkanji** [comment]
之前是觉得大家喜欢字体差距很大, 有人用12px有人用16px

**Comment by pjpjp219** [comment]
> 之前是觉得大家喜欢字体差距很大, 有人用12px有人用16px

我觉得可以把这两属性抽出来，菜单栏可以加个备注，修改大小可能导致菜单无法对齐，编辑器的字体大小各有所爱就随便我们调整了

**Comment by Black-Jay** [comment]
加上
```
.file-node-content {
  display: flex;
  align-items: center;
}
```

**Comment by Black-Jay** [comment]
这样比较舒服些
```
.file-node-content {
  display: flex;
  align-items: center;
}
.file-node-open-state {
  margin-right: 20px;
}
.file-node-icon{
  margin-right: 10px;
}
```

**Comment by pjpjp219** [comment]
> 这样比较舒服些
> 
> ```
> .file-node-content {
>   display: flex;
>   align-items: center;
> }
> .file-node-open-state {
>   margin-right: 20px;
> }
> .file-node-icon{
>   margin-right: 10px;
> }
> ```

谢谢！

**Comment by liangjingkanji** [comment]
> 这样比较舒服些
> 
> ```
> .file-node-content {
>   display: flex;
>   align-items: center;
> }
> .file-node-open-state {
>   margin-right: 20px;
> }
> .file-node-icon{
>   margin-right: 10px;
> }
> ```

怎么不来个PR
