### ISSUE TITLE
Typora 导出pdf问题

### ISSUE THREAD

**Issue by Jack9610** [liangjingkanji/DrakeTyporaTheme#61]
### 描述问题
导出的pdf在样式上与编辑的时候样式不一致，部分样式会失效

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
Typora官方的问题. 请反馈给官方

**Comment by liangjingkanji** [comment]
Duplicate of typora/typora-issues#4643
