### ISSUE TITLE
两行二级标题 自带的下划线离第二行太近

### ISSUE THREAD

**Issue by LyntNy4n** [liangjingkanji/DrakeTyporaTheme#64]
### 描述问题
二级标题长到两行以上就会有这个问题 离第二行太近 使用的字体是Fira Code 和 更纱黑体 SC
希望可以隔开一点
### 截图
![Snipaste_2022-02-24_16-48-29](https://user-images.githubusercontent.com/49772385/155490336-5057cc2b-b1bf-455d-9784-70d6403865c9.jpg)
![Snipaste_2022-02-24_16-48-43](https://user-images.githubusercontent.com/49772385/155490346-6d4800ac-8be6-4ea8-8188-19ccee1d384e.jpg)

### 系统 (建议使用最新Typora版本)
 - OS win11
 - Theme  drake-vue
 - Typora Version 1.1.4

**Comment by liangjingkanji** [comment]
也算你牛逼
