### ISSUE TITLE
请问如何更改加粗

### ISSUE THREAD

**Issue by LiXuuuu** [liangjingkanji/DrakeTyporaTheme#66]
### 描述问题
修改哪个地方可以让加粗的文字更粗一点

### 截图
![image](https://user-images.githubusercontent.com/53567817/155727452-af81665c-6338-47fc-81f4-2cb9356160bc.png)

**Comment by liangjingkanji** [comment]
我没看到你的主题版本号
你这个应该是字体没有安装粗体效果. 
字体一般都有变体比如`JetBrainsMono_Bold.ttf`或者`JetBrainsMono_Regular.ttf`

**Comment by LiXuuuu** [comment]
谢谢！安装了粗体解决

**Comment by shikinamiask** [comment]
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/122358441/7218a4cc-4faf-4063-a16a-415e1cb4f21a)
紫色主题，如图“匈牙利算法”设置加粗，但是不是太明显，一串文字多处标记加粗的时候，基本认不出来哪来着重强调了。希望能把加粗的颜色深化一下或者变一下颜色都行。
