### ISSUE TITLE
Mac 平台代办项与文字没有上下居中对齐

### ISSUE THREAD

**Issue by dongbingliu** [liangjingkanji/DrakeTyporaTheme#67]
### 描述问题
Mac 平台代办项与文字没有上下居中对齐

### 如何复现问题
Mac 平台必现

### 期望结果
上下居中对齐

### 截图
<img width="469" alt="image" src="https://user-images.githubusercontent.com/7981299/156888750-d4a10031-04e3-4400-9910-3224202c1dca.png">

### 系统 (建议使用最新Typora版本)
 - OS Mac
 - Theme  所有 DrakeTypora 主题
 - Typora Version v1.0.2

**Comment by liangjingkanji** [comment]
这个问题我很早就知道了, 不好意思我尝试解决但并没有成功. 别的主题如果使用自定义CheckBox同样有这个问题甚至更严重

**Comment by liangjingkanji** [comment]
今天脑子比较好, 修复成功

**Comment by dongbingliu** [comment]
Cool
