### ISSUE TITLE
缩进第一次渲染正常, 关闭浏览器后再次打开渲染没有缩进了

### ISSUE THREAD

**Issue by dongbingliu** [liangjingkanji/DrakeTyporaTheme#68]
### 描述问题
缩进第一次渲染正常, 关闭Typora后再次打开渲染没有缩进了

### 如何复现问题
待办项回车,按住 TAB 键, 可以正常缩进, 关闭 Typora 之后, 再次打开部分缩进渲染不正常了
- [ ] SE 渠道开发
    - [ ] Android 平台 cmake 构建
        - [ ] 正常构建出`*.so`库,加载失败 2022-03-05 未解决
    - [ ] Unity -> C# -> C++ 通讯(Android) 

### 期望结果
渲染正常缩进

### 截图
Typora 源码
<img width="818" alt="image" src="https://user-images.githubusercontent.com/7981299/156890962-d1e2fc70-5102-4f74-8b20-79d4d0b320a9.png">

关闭Typora 后重启缩进失败效果图
<img width="531" alt="image" src="https://user-images.githubusercontent.com/7981299/156890973-80a01bc6-33ff-4058-a875-acd2f878d612.png">

### 系统 (建议使用最新Typora版本)
 - OS Mac
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
我保存你这一段但是无法复现你的问题, 你录个视频看看吧
```
- [ ] SE 渠道开发
    - [ ] Android 平台 cmake 构建
        - [ ] 正常构建出`*.so`库,加载失败 2022-03-05 未解决
    - [ ] Unity -> C# -> C++ 通讯(Android) 
```

**Comment by liangjingkanji** [comment]
我的缩进是 2
<img width="720" alt="image" src="https://user-images.githubusercontent.com/21078112/156891405-529763fd-b494-41d4-88d6-85a0f87dcba5.png">

**Comment by dongbingliu** [comment]
自己测试其他的主题也有这种现象, 感谢

**Comment by dongbingliu** [comment]
> 我的缩进是 2 <img alt="image" width="720" src="https://user-images.githubusercontent.com/21078112/156891405-529763fd-b494-41d4-88d6-85a0f87dcba5.png">

设置成默认缩进 2 正常了

**Comment by liangjingkanji** [comment]
你给官方反馈下吧
