### ISSUE TITLE
源代码模式下的显示问题

### ISSUE THREAD

**Issue by ChrisGray0626** [liangjingkanji/DrakeTyporaTheme#73]
# 问题描述

在源代码模式中，出现了符号超出当前行的情况，目前只留意到符号`有这样的问题。

![image](https://user-images.githubusercontent.com/41218402/162928319-7f79c017-9a33-4964-9e41-8876c887d1e7.png)

一点小瑕疵，不影响使用，您方便的时候可以研究一下）

**Comment by liangjingkanji** [comment]
这个得官方修改了, 你去[typora issues](https://github.com/typora/typora-issues/issues)下面提问给作者吧
