### ISSUE TITLE
关闭字体连字特性, 即>= == -> 等符号粘连

### ISSUE THREAD

**Issue by liangjingkanji** [liangjingkanji/DrakeTyporaTheme#75]
连字特性(其中内置字体JetBrainsMono就自带该特效), 这是编程字体很流行的特性

解决方法

1. 修改为其他字体
2. 或者下载不带`连字`特性版本的[JetBrainsMono](https://github.com/JetBrains/JetBrainsMono)字体. 下载zip里面的`JetBrainsMonoNL`前缀即是

**Comment by liangjingkanji** [comment]
This is the ligature feature (which comes with the built-in font JetBrainsMono), which is a very popular feature of programming fonts

## resolvent

1. Modify to another font
2. Or download the JetBrainsMono font without the ligature feature version. The JetBrainsMonoNL in the download file zip

**Comment by Wzifu** [comment]
请问是下载tff，我下载了JetBrainsMonoNL-Regular.tff 已经安装，并且对照修改了font，但发现不能识别到我这个字体。

**Comment by liangjingkanji** [comment]
> 请问是下载tff，我下载了JetBrainsMonoNL-Regular.tff 已经安装，并且对照修改了font，但发现不能识别到我这个字体。

不能识别是什么意思? 你是不是安装字体没有成功?

**Comment by CloverGit** [comment]
JetBrainsMonoNL 应该改为现在 Jetbrains 的字体名称 JetBrains Mono NL
`--monospace: "JetBrains Mono NL", "Fira Code", "Cascadia Code", Menlo, "Ubuntu Mono", Consolas, HYZhengYuan; /*代码字体*/`

**Comment by liangjingkanji** [comment]
> JetBrainsMonoNL 应该改为现在 Jetbrains 的字体名称 JetBrains Mono NL `--monospace: "JetBrains Mono NL", "Fira Code", "Cascadia Code", Menlo, "Ubuntu Mono", Consolas, HYZhengYuan; /*代码字体*/`

你说的不错, 我犯了一个低级错误

**Comment by chenmingboi** [comment]
好像把对应主题.css文件body中    -webkit-font-feature-settings: "liga" on, "calt" on;的on改为0就可以了
