### ISSUE TITLE
修改字体

### ISSUE THREAD

**Issue by liangjingkanji** [liangjingkanji/DrakeTyporaTheme#76]
自定义字体大小请编辑`drake`目录下的[font.css](https://github.com/liangjingkanji/DrakeTyporaTheme/blob/master/drake/font.css#L35-L37), 点击跳转黄色背景的即为修改字体位置

`--monospace`: 代码块字体
`--text-font`: 文本字体
`--title-font`: 标题字体

可以同时设置多个字体. 如果前文字体没有安装或者不支持的语言会依次回退时候后面的字体. 所以你可以同时为中文/英文设置不同字体

```css
--monospace: "JetBrains Mono", "中文字体"
```

**Comment by lx930517** [comment]
修改之后能应用于其他主题，但是无法应用于Dark和Juejin这两个主题，请问如何解决？

**Comment by liangjingkanji** [comment]
建议开一个新的issues

你这属于很奇怪的问题, 我也无法凭空猜测, 你fork仓库修改字体后依然无效再给我查看吧

**Comment by maybe2017** [comment]
为啥我下载放在指定文件夹后 ，用任何主题都是系统字体啊？

**Comment by liangjingkanji** [comment]
> 为啥我下载放在指定文件夹后 ，用任何主题都是系统字体啊？

为什么不安装字体而是放到指定文件夹，什么文档有指定过文件夹吗？

**Comment by maybe2017** [comment]
> > 为啥我下载放在指定文件夹后 ，用任何主题都是系统字体啊？
> 
> 为什么不安装字体而是放到指定文件夹，什么文档有指定过文件夹吗？

是这样的，我按照安装方法将解压后的drake文件夹及css文件放置在 theme目录下，重启后，选择任何主题都只是改变了颜色，但是字体仍然是系统字体，我不知道是哪里出现了问题；
唯一不同的是，我把Typora所有默认的主题都删除了，我不知道这样是否会有影响；
问题截图：https://note.youdao.com/s/OafM3Ro2
麻烦帮我看下嘛..

**Comment by liangjingkanji** [comment]
你下载字体后有安装字体吗?

**Comment by maybe2017** [comment]
> 
752854893这个QQ群 不存在啊，我搜不到，你们最新的群号是多少呢
