### ISSUE TITLE
是否有方法调整latex公式的大小?

### ISSUE THREAD

**Issue by LyntNy4n** [liangjingkanji/DrakeTyporaTheme#79]
默认情况下 公式的字体比正文字体略小 对一些上标下标就看得比较费劲
![image](https://user-images.githubusercontent.com/49772385/164958405-edfe8a30-c3df-44a1-96da-6f1ac439ed06.png)
简单搜了下 有人说可以在主题下加下述代码,但是好像没有效果
`.md-math-block.MathJax {
    font-size: 1.2rem !important;
}
`
不知道有什么其他的方法?

**Comment by liangjingkanji** [comment]
我也没修改过公式

**Comment by LyntNy4n** [comment]
https://github.com/typora/typora-issues/issues/3475#issuecomment-890507683
问题解决了 这个有用

**Comment by liangjingkanji** [comment]
能否提供修改后的效果提PR上来
