### ISSUE TITLE
字体偏小

### ISSUE THREAD

**Issue by saodis** [liangjingkanji/DrakeTyporaTheme#82]
### 描述问题
字体偏小，建议字体调大一些，不然用这个主题，需要到 typora 中自定义字体大小，而切换其他主题又需要设置为自动，不然字体又大了。

所以建议这个主题字体稍微大一些

**Comment by liangjingkanji** [comment]
为什么切换到其他字体要设置为自动?  全部都固定设置不就一样吗?

**Comment by saodis** [comment]
@liangjingkanji 不切回来，感觉有差别，你可以试试。只是建议。

**Comment by liangjingkanji** [comment]
估计是字体区别的问题

**Comment by liangjingkanji** [comment]
我不考虑全局缩小字号, 我提供修改主题字体的方案吧

**Comment by liangjingkanji** [comment]
可以阅读[常见问题](https://github.com/liangjingkanji/DrakeTyporaTheme/blob/master/issues.md)修改字体大小
