### ISSUE TITLE
显示异常, 符号连字

### ISSUE THREAD

**Issue by saodis** [liangjingkanji/DrakeTyporaTheme#84]
### 描述问题
这个显示是不是有点问题？用自带的主题是正常的
![image](https://user-images.githubusercontent.com/51149477/166137868-fffdf257-a031-414d-83dc-04258df7f9dc.png)

### 如何复现问题
代码块内输入 `<<-`

### 系统 (建议使用最新Typora版本)
 - OS: windows 10 
 - Theme: 所有
 - Typora Version: 1.2.4

**Comment by liangjingkanji** [comment]
#70 

这是主题自带字体的连字特性

**Comment by saodis** [comment]
@liangjingkanji 看着很别扭😂 我改字体看看
