### ISSUE TITLE
drake-juejin 导出HTML之后h2的underline会消失

### ISSUE THREAD

**Issue by ShunyangLi** [liangjingkanji/DrakeTyporaTheme#88]
### 描述问题

drake-juejin 导出HTML之后h2的underline会消失

**Comment by liangjingkanji** [comment]
https://github.com/typora/typora-issues

你去官方反馈下这个问题吧, Typora导出的时候会删除样式

**Comment by liangjingkanji** [comment]
官方导出的html部分样式会消失, 请给官方反馈, 这是主题无法修复的问题

Duplicate of typora/typora-issues#4643
