### ISSUE TITLE
Drake-google主题要如何渲染出四方圆角的效果(高亮模式下)

### ISSUE THREAD

**Issue by imboye** [liangjingkanji/DrakeTyporaTheme#89]
### 描述问题
想问一下，要如何实现”期望结果“截图中那种四四方方圆角的效果。我使用”高亮“样式时，只能出现那种椭圆型的效果

### 如何复现问题
复现问题的语法：==感谢Drake作者提供的主题==
### 期望结果
<img width="743" alt="Screen Shot 2022-06-26 at 9 15 21 PM" src="https://user-images.githubusercontent.com/38388604/175816063-890bbc86-00e8-4f3e-be96-db43aaf54afb.png">

### 截图

<img width="392" alt="Screen Shot 2022-06-26 at 9 19 57 PM" src="https://user-images.githubusercontent.com/38388604/175816111-ce2bc6e6-23aa-455a-a3da-5d38456da517.png">

### 系统 (建议使用最新Typora版本)
 - OS： Mac
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
打开readme看下

**Comment by imboye** [comment]
可以了。原来是要用<kbd>标签，感谢作者大大。非常喜欢你提供的Drake主题，太好看了，已star。

**Comment by liangjingkanji** [comment]
我的目的就是让大家学习更愉悦，欢迎成为共同作者
