### ISSUE TITLE
当光标处于三级主题/四级主题/五级主题/六级主题上时，Typora左侧无法出现h3/h4/h5/h6等字样

### ISSUE THREAD

**Issue by imboye** [liangjingkanji/DrakeTyporaTheme#90]
### 描述问题
作者大大，想问一下，当光标处于三级主题/四级主题/五级主题/六级主题上时，左侧无法出现h3/h4/h5/h6的字样。

### 如何复现问题
复现语法: 
### 期望结果
<img width="478" alt="Screen Shot 2022-06-27 at 12 12 43 PM" src="https://user-images.githubusercontent.com/38388604/175859044-e090cad8-9d51-422e-9498-27e8e5b4d1c2.png">

### 截图
应用Drake主题时的效果图: 
<img width="478" alt="Screen Shot 2022-06-27 at 12 12 35 PM" src="https://user-images.githubusercontent.com/38388604/175859080-1cdbb35e-4e31-430a-9e0b-a87b46a55ef0.png">

### 系统 (建议使用最新Typora版本)
 - OS: Mac
 - Theme 
 - Typora Version: 最新版本

**Comment by liangjingkanji** [comment]
这个主题不支持

**Comment by imboye** [comment]
那这个可以实现不？容易不？

**Comment by liangjingkanji** [comment]
我不记得了, 应该不难吧

**Comment by imboye** [comment]
我看了CSS文件中有以下一段代码
```
#write > h3.md-focus:before {
    left: -0.5625rem;
    top: .375rem;
}
#write > h4.md-focus:before {
    left: -1.5625rem;
    top: .285714286rem;
}
#write > h5.md-focus:before {
    left: -1.5625rem;
    top: .285714286rem;
}
#write > h6.md-focus:before {
    left: -1.5625rem;
    top: .285714286rem;
}
```
好像就是用来在标题前插入`hx`字样，但是没有生效。我也不知道怎么修改了。

**Comment by liangjingkanji** [comment]
我觉得无意义, 标题不需要知道自己是多少几级, 如果你想明确层级应该查看`目录结构`或者使用序列号(例如`1.1.2`)

本问题将关闭
