### ISSUE TITLE
Checkboxes not rendered when exporting to pdf. 

### ISSUE THREAD

**Issue by ironhak** [liangjingkanji/DrakeTyporaTheme#91]
Hi, first of all thank's for this theme collection. I really enjoy it. I do not understand chinese (or Japanese, sorry I can't tell the difference), so please answer in english if you can, thank's. 

There is an issue with this theme, checkboxes does not get rendered on pdf exports.

Hope you can solve this, thank's.

**Comment by liangjingkanji** [comment]
This is an official Typora issue, The theme cannot be repaired

duplication #89
