### ISSUE TITLE
xml代码块的注释内容会变形

### ISSUE THREAD

**Issue by formzs** [liangjingkanji/DrakeTyporaTheme#92]
### 描述问题
xml代码块的注释内容会变形，如下
![image](https://user-images.githubusercontent.com/23046631/177460909-f50b4f45-f1cd-45ff-84d9-be6ac1abafa2.png)
### 系统(建议使用最新Typora版本)
- OS：win10
- Theme：Drake全系列
- Typora Version：1.3.8

**Comment by liangjingkanji** [comment]
这是字体特性: `ligatures` 关闭方法 #75
