### ISSUE TITLE
Drake Black中的代码块内 注释文字的颜色如何修改？

### ISSUE THREAD

**Issue by juanvon** [liangjingkanji/DrakeTyporaTheme#94]
### 描述问题
Drake Black主题中，本身背景就偏暗，现在代码块内的注释颜色也是深灰色，有时候很难看清，请问该修改哪个地方？

### 截图
![image](https://user-images.githubusercontent.com/87421767/180145888-da4e6609-634f-4f21-9af8-c2a8dde2aa56.png)

### 系统 (建议使用最新Typora版本)
 - OS win10
 - Theme Drake Black
 - Typora Version 1.0.3

**Comment by liangjingkanji** [comment]
在我的设计中注释不应该抢焦点, 你是所有暗色主题注释都看不清楚还是就Black

**Comment by juanvon** [comment]
> 在我的设计中注释不应该抢焦点, 你是所有暗色主题注释都看不清楚还是就Black

都不太清楚，注释的颜色会随着主题颜色变化一些，但是Black的时候最不清楚，和底色比较接近了。

**Comment by liangjingkanji** [comment]
你是希望注释和普通文字一样清楚是吗? 还是希望直接显示绿色?

**Comment by juanvon** [comment]
> 你是希望注释和普通文字一样清楚是吗? 还是希望直接显示绿色?

直接显示绿色就好，但是我始终没有找到设置的地方。

**Comment by liangjingkanji** [comment]
在主题末尾找到`.cm-s-inner .cm-comment`或者`.cm-s-inner span.cm-comment`修改里面的颜色值即可修改注释颜色

例如Black主题的[注释高亮颜色](https://github.com/liangjingkanji/DrakeTyporaTheme/blob/38a671f03466b7ea2b2f86ffebc85d9f6dd140b4/drake-dark.css#L1093) (点击打开)

**Comment by liangjingkanji** [comment]
我不倾向于注释比代码本身还明显, 估只调整Black主题注释颜色更亮, 你可以按照上面的描述自行修改颜色

**Comment by juanvon** [comment]
> 我不倾向于注释比代码本身还明显, 估只调整Black主题注释颜色更亮, 你可以按照上面的描述自行修改颜色

懂了，非常感谢！
