### ISSUE TITLE
建议: js代码块中, js语法里面的=== 被显示为3条横线 , 这样对于js不太友好

### ISSUE THREAD

**Issue by Ricardo-Charles** [liangjingkanji/DrakeTyporaTheme#95]
### 描述问题
在js代码块中, 语法里面的 === 被自动改为了3条横线

![image](https://user-images.githubusercontent.com/44394716/182008362-08f3062c-f348-443e-8dad-cec6c2c84e41.png)

### 系统 (建议使用最新Typora版本)
 - OS : Win10
 - Theme  : Drake-Light.css
 - Typora Version : 最新版

**Comment by liangjingkanji** [comment]
README有提到, 这是字体的连字特性, 适用于编程的字体一般都自带该特性

<img width="701" alt="image" src="https://user-images.githubusercontent.com/21078112/182008459-58209893-98c4-4c89-aedb-9260e9dacee4.png">

**Comment by Ricardo-Charles** [comment]
谢谢东哥, 已经解决, 东哥考虑加个  Sponsor 吗? 我来给东哥打赏, 这个theme 帮我了很多, 东哥也一直在无偿付出

**Comment by liangjingkanji** [comment]
为了持续维持项目更新, 可以考虑
