### ISSUE TITLE
希望主题不要影响到代码字符的显示

### ISSUE THREAD

**Issue by aerfensi** [liangjingkanji/DrakeTyporaTheme#96]
### 描述问题
![image](https://user-images.githubusercontent.com/23309953/182991118-f70ac90e-7bab-41ec-bcf6-e44bb1e21f72.png)

### 期望结果

希望能和GitHub主题一样展示原本输入的字符

![image](https://user-images.githubusercontent.com/23309953/182991232-c56a01cb-1c8a-4eef-bf4f-6350fb88c99e.png)

### 系统 (建议使用最新Typora版本)
 - OS：Windows 10
 - Theme  drake-material
 - Typora Version  1.3.8

**Comment by liangjingkanji** [comment]
Duplicate of #75
