### ISSUE TITLE
表格样式显示bug

### ISSUE THREAD

**Issue by 7foxx** [liangjingkanji/DrakeTyporaTheme#97]
### 描述问题
表格的调整属性显示与标题重叠

### 如何复现问题
在标题下方创建表格

### 期望结果
表格和标题之间有合适距离

### 截图
<img width="466" alt="image" src="https://user-images.githubusercontent.com/87110607/183277368-c04f0cc9-51cf-44ea-9dfa-851750d62bae.png">

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
请告诉我是什么风格的主题, 描述清楚版本信息

**Comment by 7foxx** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/87110607/183277439-22cc10cb-701b-4a94-b135-dc45155d76f0.png">
所有主题风格

**Comment by liangjingkanji** [comment]
我无法复现此问题

<img width="447" alt="image" src="https://user-images.githubusercontent.com/21078112/183277462-1d738f66-6ce0-4943-924a-f7d107a54956.png">

**Comment by liangjingkanji** [comment]
这是Typora官方的问题, 非主题能解决的, 请反馈给官方

**Comment by 7foxx** [comment]
> 

鼠标移到” 推荐字体“上

**Comment by 7foxx** [comment]
> 这是Typora官方的问题，非主题能解决的，请反馈给官方

ok

**Comment by liangjingkanji** [comment]
Typora自带主题也存在该问题, 不过我认为也许尝试增加所有标题的下边距来解决此问题

**Comment by 7foxx** [comment]
> Typora自带主题也存在该问题, 不过我认为也许尝试增加所有标题的下边距来解决此问题

好的

**Comment by liangjingkanji** [comment]
更新主题试下, 另外新增了两款主题

**Comment by 7foxx** [comment]
> 更新主题试下, 另外新增了两款主题

ok

**Comment by 7foxx** [comment]
> 更新主题试下, 另外新增了两款主题

没问题了，这个是修改的标题下边距吧，我觉得也可以尝试一下增加表格的上边距。不过现在看着也很舒适

**Comment by liangjingkanji** [comment]
我认为你提供的思路更好

**Comment by 7foxx** [comment]
> 我认为你提供的思路更好

谢谢东哥的肯定！

**Comment by liangjingkanji** [comment]
我重新修改了下你重下吧
为了视觉效果h2标题我还是略微提升了一点底部间距(无关乎此问题)

**Comment by 7foxx** [comment]
> 我重新修改了下你重下吧 为了视觉效果h2标题我还是略微提升了一点底部间距(无关乎此问题)

好的

**Comment by 7foxx** [comment]
> 我重新修改了下你重下吧 为了视觉效果h2标题我还是略微提升了一点底部间距(无关乎此问题)

完美了，vue3这款主题非常好看，:+1:

**Comment by liangjingkanji** [comment]
但是你却才star我, 实在是令我失望

**Comment by 7foxx** [comment]
> 但是你却才star我, 实在是令我失望

哈哈哈点了哈
