### ISSUE TITLE
如何调整侧边栏的字体大小和间距？

### ISSUE THREAD

**Issue by qizhengyang2017** [liangjingkanji/DrakeTyporaTheme#98]
### 描述问题
我在typora的外观设置里自定义了字体大小（14 px），侧边栏的字体也同时跟着变大。但是感觉侧边栏的字体比正文字体大很多，想调整一下

### 系统 (建议使用最新Typora版本)
 - OS: mac 12.5
 - Theme: drake dark
 - Typora Version: 1.2.4

**Comment by qizhengyang2017** [comment]
下载了这个主题的最新版本，这个问题不存在了。感谢作者开发了这个主题。还有请问是否有办法自动更新主题呢？

**Comment by liangjingkanji** [comment]
1. 直接拉取github到主题根目录下
2. 让Typora作者支持该功能
